import type { StyleArchetype, StyleDNA } from "../schema";

/**
 * One full base DNA per archetype. To synthesize a style for a creator that is
 * not in the preset list: pick the nearest archetype, start from its base, then
 * override with what is known or measured (ASL, caption look, palette, fonts,
 * signature tells). Values here are approx best-practice defaults.
 */
export const ARCHETYPE_BASES: Record<StyleArchetype, StyleDNA> = {
  retention_entertainment: {
    id: "base-retention_entertainment",
    name: "Retention entertainment (base)",
    category: "custom",
    archetype: "retention_entertainment",
    description:
      "Base for challenge/stunt/entertainment creators: escalating stakes, fast hard cuts, an SFX on most cuts, bright saturated grade.",
    tags: ["base", "entertainment", "challenge", "high-energy", "youtube"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 300, typical: 720, max: 1500 },
    },
    pacing: {
      aslSec: 2.4,
      cutStyle: "hard",
      beatSync: "loose",
      maxSilenceMs: 250,
      keepFillers: false,
      hook: "Open on the most extreme moment and state premise + stakes in the first sentence; preview the escalation in 3-6 quick shots; pay off the title promise within 30s.",
      ending: "abrupt",
      punchIn: { scale: 1.2, perMin: 6, durFrames: 3 },
    },
    grade: {
      exposure: 0.1,
      contrast: 1.15,
      saturation: 1.2,
      vibrance: 0.2,
      temperature: 0.04,
      tint: 0,
      highlights: 0,
      shadows: -0.06,
      fade: 0,
      lut: "vivid-pop",
      vignette: 0.05,
      grain: 0,
      look: "bright saturated pop",
    },
    palette: {
      background: "#0E0E10",
      foreground: "#FFFFFF",
      accents: ["#FFD700", "#36D15A", "#FF3B30"],
      rule: "stroked white/yellow type; green for money, red for time",
    },
    typography: {
      title: {
        fontFamily: "Luckiest Guy",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.01,
        color: "#FFFFFF",
        stroke: { color: "#000000", width: 10 },
        shadow: { color: "rgba(0,0,0,0.6)", blur: 8, x: 0, y: 4 },
        sizePctH: 11,
      },
      body: {
        fontFamily: "Montserrat",
        fontWeight: 800,
        textTransform: "uppercase",
        letterSpacing: 0,
        color: "#FFFFFF",
        stroke: { color: "#000000", width: 6 },
        sizePctH: 4.2,
      },
      callout: {
        fontFamily: "Bangers",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.02,
        color: "#FFD700",
        stroke: { color: "#000000", width: 8 },
        sizePctH: 8,
      },
    },
    captions: {
      mode: "callout_only",
      style: {
        fontFamily: "Bangers",
        fontWeight: 400,
        fontSize: 84,
        color: "#FFFFFF",
        activeColor: "#FFD700",
        textTransform: "uppercase",
        stroke: { color: "#000000", width: 8 },
        shadow: { color: "rgba(0,0,0,0.6)", blur: 8, x: 0, y: 4 },
        animation: "pop",
        combineMs: 400,
        maxWordsPerPage: 3,
      },
      yPct: 0.7,
    },
    transitions: {
      primary: "cut",
      secondary: ["zoom-in", "whip", "flash"],
      durationFrames: 4,
      frequency: 0.1,
      avoid: ["dissolves", "slow intros", "dead air"],
    },
    motion: {
      enter: "pop",
      exit: "zoom",
      easing: "bouncy",
      textAnimation: "slam",
      textUnit: "word",
      stagger: 2,
      idleLoop: "pulse",
      kenBurns: false,
      shake: true,
      motionBlur: true,
      overshootPct: 20,
    },
    overlays: ["counter", "money-counter", "countdown", "arrow-callout", "circle-highlight", "chapter-card", "subscribe-cta"],
    sound: {
      music: "high-energy hybrid score that changes at every story beat",
      bpm: [115, 150],
      sfx: ["whoosh", "impact", "riser", "ding", "pop", "bass-hit"],
      sfxPerMin: 25,
      duckDb: 14,
    },
    signature: [
      "Payoff-first cold open with explicit stakes",
      "Escalation tracked by on-screen counters",
      "Hard cuts with SFX and snap punch-ins",
      "Abrupt ending after the payoff",
    ],
    avoid: ["slow intros", "soft transitions", "moody grades", "outros"],
    agentNotes:
      "Synthesis base. Override ASL from the creator (MrBeast-style ~2.2s, sub-1s for shorts-first creators). Keep a re-engagement beat every ~3 minutes in long-form, one persistent counter, an SFX on most cuts, punch-ins on reactions, and end within seconds of the payoff.",
  },
  talking_head_short: {
    id: "base-talking_head_short",
    name: "Talking-head short (base)",
    category: "custom",
    archetype: "talking_head_short",
    description:
      "Base for vertical talking-head shorts: speech on frame 0, bold 1-3 word captions with one keyword color, jump cuts and punch-ins.",
    tags: ["base", "shorts", "reels", "tiktok", "captions", "talking-head"],
    format: {
      aspect: "9:16",
      fps: 30,
      durationSec: { min: 15, typical: 45, max: 90 },
    },
    pacing: {
      aslSec: 2.5,
      cutStyle: "jump",
      beatSync: "none",
      maxSilenceMs: 250,
      keepFillers: false,
      hook: "Speech on frame 0: a bold claim or question, captions from the first frame; the promise is complete by ~2s and the first payoff lands by ~2.5s.",
      ending: "abrupt",
      punchIn: { scale: 1.15, perMin: 5, durFrames: 0 },
    },
    grade: {
      exposure: 0,
      contrast: 1.12,
      saturation: 1.02,
      vibrance: 0.05,
      temperature: 0.05,
      tint: 0,
      highlights: -0.1,
      shadows: -0.12,
      fade: 0,
      vignette: 0.15,
      grain: 0,
      look: "clean, slightly dark background, warm skin",
    },
    palette: {
      background: "#0A0A0A",
      foreground: "#FFFFFF",
      accents: ["#FFE14D", "#39FF14"],
      rule: "white captions + one keyword color",
    },
    typography: {
      title: {
        fontFamily: "Montserrat",
        fontWeight: 900,
        textTransform: "uppercase",
        letterSpacing: -0.01,
        color: "#FFFFFF",
        stroke: { color: "#000000", width: 8 },
        sizePctH: 5,
      },
      body: {
        fontFamily: "Montserrat",
        fontWeight: 700,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFFFFF",
        stroke: { color: "#000000", width: 4 },
        sizePctH: 2.8,
      },
      callout: {
        fontFamily: "Montserrat",
        fontWeight: 900,
        textTransform: "uppercase",
        letterSpacing: -0.01,
        color: "#FFE14D",
        stroke: { color: "#000000", width: 8 },
        sizePctH: 6,
      },
    },
    captions: {
      mode: "word_group",
      style: {
        fontFamily: "Montserrat",
        fontWeight: 900,
        fontSize: 96,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        emphasisColor: "#FFE14D",
        textTransform: "uppercase",
        stroke: { color: "#000000", width: 9 },
        shadow: { color: "rgba(0,0,0,0.5)", blur: 8, x: 0, y: 4 },
        animation: "pop",
        combineMs: 450,
        maxWordsPerPage: 3,
        lineHeight: 1,
        showEmoji: false,
      },
      yPct: 0.64,
    },
    transitions: {
      primary: "cut",
      secondary: [],
      durationFrames: 0,
      frequency: 0,
      avoid: ["transition effects", "intro title cards", "outros"],
    },
    motion: {
      enter: "pop",
      exit: "fade",
      easing: "snappy",
      textAnimation: "pop",
      textUnit: "word",
      stagger: 0,
      kenBurns: false,
      shake: false,
      motionBlur: false,
      overshootPct: 8,
    },
    overlays: ["emoji-pop", "arrow-callout", "progress-bar"],
    sound: {
      music: "subtle low-energy bed or none",
      bpm: [80, 100],
      sfx: ["pop", "whoosh"],
      sfxPerMin: 4,
      duckDb: 20,
    },
    signature: [
      "Speech on frame 0, payoff by 2.5s",
      "1-3 word bold captions in the lower middle",
      "Jump cuts alternating framing",
      "Ends on the last payoff word",
    ],
    avoid: ["preamble", "small captions", "transition effects", "captions over the face"],
    agentNotes:
      "Synthesis base. Measured shorts laws: hook <=2.5s, a visual change every 3-8s, payoff at 55-85% of runtime. Keep captions in the 9:16 safe zone (avoid top ~12% and bottom ~20%), 1-3 words per page. Decide caption casing/stroke from the creator: caps + stroke for hype, mixed case + shadow for calm experts.",
  },
  podcast_clip: {
    id: "base-podcast_clip",
    name: "Podcast clip (base)",
    category: "custom",
    archetype: "podcast_clip",
    description: "Base for vertical podcast/interview clips: speaker-switch cutting, keyword captions, a pulled-forward hook, dry audio.",
    tags: ["base", "podcast", "interview", "clips", "shorts"],
    format: {
      aspect: "9:16",
      fps: 30,
      durationSec: { min: 30, typical: 75, max: 140 },
    },
    pacing: {
      aslSec: 5,
      cutStyle: "hard",
      beatSync: "none",
      maxSilenceMs: 800,
      keepFillers: true,
      hook: "Move the strongest sentence to 0s (optionally muting its key words) or show a title banner naming the payoff for the first ~5s.",
      ending: "abrupt",
    },
    grade: {
      exposure: -0.05,
      contrast: 1.12,
      saturation: 0.95,
      vibrance: 0,
      temperature: 0.05,
      tint: 0,
      highlights: -0.15,
      shadows: -0.12,
      fade: 0,
      vignette: 0.2,
      grain: 0.02,
      look: "dark studio with warm practicals",
    },
    palette: {
      background: "#0B0B0B",
      foreground: "#FFFFFF",
      accents: ["#FFD60A", "#FFFFFF"],
      rule: "one color per speaker for captions",
    },
    typography: {
      title: {
        fontFamily: "Anton",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.01,
        color: "#FFFFFF",
        stroke: { color: "#000000", width: 8 },
        sizePctH: 5,
      },
      body: {
        fontFamily: "Inter",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFFFFF",
        shadow: { color: "rgba(0,0,0,0.6)", blur: 10, x: 0, y: 2 },
        sizePctH: 2.6,
      },
      callout: {
        fontFamily: "Anton",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.01,
        color: "#FFD60A",
        stroke: { color: "#000000", width: 8 },
        sizePctH: 4,
      },
    },
    captions: {
      mode: "word_group",
      style: {
        fontFamily: "Anton",
        fontWeight: 400,
        fontSize: 92,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        emphasisColor: "#FFD60A",
        textTransform: "uppercase",
        stroke: { color: "#000000", width: 10 },
        animation: "none",
        combineMs: 500,
        maxWordsPerPage: 3,
        lineHeight: 1,
      },
      yPct: 0.65,
    },
    transitions: {
      primary: "cut",
      secondary: [],
      durationFrames: 0,
      frequency: 0,
      avoid: ["music beds under the conversation", "transition effects", "heavy b-roll"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "ease-out",
      textAnimation: "none",
      textUnit: "word",
      stagger: 0,
      kenBurns: false,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["kinetic-title", "lower-third", "end-card", "split-screen"],
    sound: {
      music: "none (dry conversation)",
      bpm: [70, 90],
      sfx: [],
      sfxPerMin: 0,
      duckDb: 20,
    },
    signature: [
      "The camera follows the voice",
      "Pulled-forward hook or payoff banner",
      "Keyword-only captions colored by speaker",
      "Dry audio with natural pauses",
    ],
    avoid: ["music and SFX", "full-transcript captions", "zoom gimmicks"],
    agentNotes:
      "Synthesis base. Measured DOAC-style numbers: cuts every 4.1-6.3s, reaction cutaways 1-1.5s, payoff at 55-80%, 60-140s total, b-roll under ~6.5%. For two speakers in one frame use a top/bottom split-screen. Keep laughter and meaningful silences.",
  },
  talking_head_edu: {
    id: "base-talking_head_edu",
    name: "Educational talking head (base)",
    category: "custom",
    archetype: "talking_head_edu",
    description:
      "Base for explainer/educator creators on camera: warm bright studio, numbered chapter cards, evidence screenshots, friendly pop graphics.",
    tags: ["base", "education", "talking-head", "explainer", "youtube"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 360, typical: 900, max: 1500 },
    },
    pacing: {
      aslSec: 4.5,
      cutStyle: "jump",
      beatSync: "none",
      maxSilenceMs: 250,
      keepFillers: true,
      hook: "'You'-framed problem plus a promise of N concrete takeaways within 10s; no preamble.",
      ending: "cta",
      punchIn: { scale: 1.12, perMin: 2, durFrames: 8 },
    },
    grade: {
      exposure: 0.08,
      contrast: 1.05,
      saturation: 1.05,
      vibrance: 0.08,
      temperature: 0.08,
      tint: 0,
      highlights: -0.15,
      shadows: 0.04,
      fade: 0.03,
      lut: "warm-vlog",
      vignette: 0,
      grain: 0,
      look: "warm bright studio",
    },
    palette: {
      background: "#F5F1EA",
      foreground: "#1F1F1F",
      accents: ["#FFD400", "#3B5BDB"],
      rule: "warm neutrals + one highlight color",
    },
    typography: {
      title: {
        fontFamily: "Inter",
        fontWeight: 800,
        textTransform: "none",
        letterSpacing: -0.02,
        color: "#FFFFFF",
        shadow: { color: "rgba(0,0,0,0.35)", blur: 10, x: 0, y: 3 },
        sizePctH: 7,
      },
      body: {
        fontFamily: "Inter",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#FFFFFF",
        shadow: { color: "rgba(0,0,0,0.35)", blur: 8, x: 0, y: 2 },
        sizePctH: 3.6,
      },
      callout: {
        fontFamily: "Caveat",
        fontWeight: 700,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFD400",
        sizePctH: 6,
      },
    },
    captions: {
      mode: "callout_only",
      style: {
        fontFamily: "Inter",
        fontWeight: 800,
        fontSize: 60,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        emphasisColor: "#FFD400",
        textTransform: "none",
        shadow: { color: "rgba(0,0,0,0.5)", blur: 10, x: 0, y: 3 },
        animation: "pop",
        combineMs: 700,
        maxWordsPerPage: 5,
      },
      yPct: 0.8,
    },
    transitions: {
      primary: "cut",
      secondary: ["slide", "wipe", "zoom-in"],
      durationFrames: 10,
      frequency: 0.08,
      avoid: ["glitch or flash transitions", "dense meme editing"],
    },
    motion: {
      enter: "pop",
      exit: "fade",
      easing: "playful",
      textAnimation: "pop",
      textUnit: "word",
      stagger: 2,
      idleLoop: "float",
      kenBurns: true,
      shake: false,
      motionBlur: false,
      overshootPct: 10,
    },
    overlays: ["chapter-card", "kinetic-title", "highlighter-sweep", "quote-card", "browser-window", "line-chart"],
    sound: {
      music: "lo-fi / acoustic / chill pop beds",
      bpm: [75, 95],
      sfx: ["pop", "click", "whoosh"],
      sfxPerMin: 6,
      duckDb: 18,
    },
    signature: [
      "Numbered chapter/principle cards",
      "Evidence on screen: studies, articles, charts with highlights",
      "Friendly direct address in a warm, bright set",
    ],
    avoid: ["claims without visuals", "aggressive SFX", "dark grades"],
    agentNotes:
      "Synthesis base. Measured educator long-form: 7.7-9.3 cuts/min, median shot 3-6.5s, 0 burned captions in long-form, fillers kept. Put a visual (card, screenshot, b-roll, chart) on every new claim; one punch-in every 30-60s; chapter cards for each numbered point.",
  },
  talking_head_premium: {
    id: "base-talking_head_premium",
    name: "Premium talking head (base)",
    category: "custom",
    archetype: "talking_head_premium",
    description:
      "Base for premium business/self-improvement talking heads: cinematic b-roll, restrained motion graphics, blur-fade text, print-film grade.",
    tags: ["base", "premium", "business", "cinematic", "talking-head"],
    format: {
      aspect: "16:9",
      fps: 24,
      durationSec: { min: 480, typical: 1200, max: 1800 },
    },
    pacing: {
      aslSec: 3.8,
      cutStyle: "mixed",
      beatSync: "loose",
      maxSilenceMs: 250,
      keepFillers: false,
      hook: "Result or contrarian claim plus on-screen proof within 15s; open 2-3 loops.",
      ending: "cta",
      punchIn: { scale: 1.08, perMin: 2, durFrames: 12 },
    },
    grade: {
      exposure: 0,
      contrast: 1.12,
      saturation: 0.92,
      vibrance: 0.05,
      temperature: 0.05,
      tint: 0,
      highlights: -0.25,
      shadows: -0.06,
      fade: 0.02,
      lut: "film-print",
      vignette: 0.18,
      grain: 0.08,
      look: "luxury cinematic print-film look, shallow depth of field",
    },
    palette: {
      background: "#0D0F12",
      foreground: "#F5F5F5",
      accents: ["#C9A24B", "#2F4858"],
      rule: "dark neutrals + one accent derived from the footage (60/30/10)",
    },
    typography: {
      title: {
        fontFamily: "Montserrat",
        fontWeight: 700,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#F5F5F5",
        sizePctH: 7,
      },
      body: {
        fontFamily: "Figtree",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: 0,
        color: "#E8E8E8",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Montserrat",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.08,
        color: "#C9A24B",
        sizePctH: 2.8,
      },
    },
    captions: {
      mode: "word_by_word",
      style: {
        fontFamily: "Montserrat",
        fontWeight: 700,
        fontSize: 58,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        emphasisColor: "#C9A24B",
        textTransform: "none",
        shadow: { color: "rgba(0,0,0,0.5)", blur: 12, x: 0, y: 3 },
        animation: "fade",
        combineMs: 700,
        maxWordsPerPage: 4,
      },
      yPct: 0.78,
    },
    transitions: {
      primary: "cut",
      secondary: ["fade", "blur"],
      durationFrames: 10,
      frequency: 0.08,
      avoid: ["cartoon fonts", "bouncy springs", "meme SFX"],
    },
    motion: {
      enter: "rise-blur",
      exit: "blur",
      easing: "smooth",
      textAnimation: "rise-blur",
      textUnit: "word",
      stagger: 3,
      idleLoop: "drift",
      kenBurns: true,
      shake: false,
      motionBlur: true,
      overshootPct: 4,
    },
    overlays: ["grid-background", "browser-window", "stat-grid", "lower-third", "chapter-card", "glow-orbs"],
    sound: {
      music: "uplifting cinematic piano + strings",
      bpm: [80, 110],
      sfx: ["whoosh", "click", "riser"],
      sfxPerMin: 6,
      duckDb: 15,
    },
    signature: [
      "Cinematic b-roll between talking-head beats",
      "Blur-fade word reveals and restrained UI cards",
      "Print-film grade with one derived accent",
    ],
    avoid: ["stroked caps captions", "neon palettes", "fast meme cuts"],
    agentNotes:
      "Synthesis base. Front-load motion graphics (4-10 per minute in the intro, ~2 per minute after) and trigger them on claims, numbers, chapter changes and proof. Fast-out/slow-in easing (350-500ms), <=4% overshoot. Derive the palette from the footage accent.",
  },
  tech_review_premium: {
    id: "base-tech_review_premium",
    name: "Premium tech review (base)",
    category: "custom",
    archetype: "tech_review_premium",
    description:
      "Base for premium product reviewers: thesis first, slow precise product b-roll on dark backgrounds, minimal type, a long verdict.",
    tags: ["base", "tech", "review", "product", "premium"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 420, typical: 780, max: 1200 },
    },
    pacing: {
      aslSec: 5.5,
      cutStyle: "hard",
      beatSync: "none",
      maxSilenceMs: 250,
      keepFillers: false,
      hook: "Thesis sentence in ~2-3s over fast product b-roll, then a short branded sting.",
      ending: "outro_card",
    },
    grade: {
      exposure: 0,
      contrast: 1.1,
      saturation: 0.95,
      vibrance: 0,
      temperature: -0.03,
      tint: 0,
      highlights: -0.2,
      shadows: -0.05,
      fade: 0,
      vignette: 0.1,
      grain: 0,
      look: "clean neutral matte with controlled highlights",
    },
    palette: {
      background: "#0B0B0C",
      foreground: "#FFFFFF",
      accents: ["#E5202B", "#9A9A9E"],
      rule: "dark neutrals + one accent (brand or product color)",
    },
    typography: {
      title: {
        fontFamily: "Barlow Condensed",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.03,
        color: "#FFFFFF",
        sizePctH: 6,
      },
      body: {
        fontFamily: "Barlow Condensed",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: 0.02,
        color: "#9A9A9E",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Barlow Condensed",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.04,
        color: "#E5202B",
        sizePctH: 3,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Barlow Condensed",
        fontWeight: 500,
        fontSize: 52,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "none",
        shadow: { color: "rgba(0,0,0,0.6)", blur: 8, x: 0, y: 2 },
        animation: "fade",
        combineMs: 1200,
        maxWordsPerPage: 8,
      },
      yPct: 0.86,
    },
    transitions: {
      primary: "cut",
      secondary: ["dip-to-black", "fade"],
      durationFrames: 10,
      frequency: 0.03,
      avoid: ["flashy transitions", "burned captions", "split screens"],
    },
    motion: {
      enter: "mask-reveal",
      exit: "fade",
      easing: "smooth",
      textAnimation: "mask-up",
      textUnit: "line",
      stagger: 3,
      idleLoop: "drift",
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 0,
    },
    overlays: ["spec-card", "lower-third", "logo-reveal", "end-card", "device-frame"],
    sound: {
      music: "chill instrumental electronic beds",
      bpm: [80, 100],
      sfx: ["whoosh", "click"],
      sfxPerMin: 4,
      duckDb: 20,
    },
    signature: [
      "Slow, precise product orbits on dark backgrounds",
      "One spec card, minimal labels",
      "Long uninterrupted verdict near the end",
    ],
    avoid: ["meme inserts", "punch-in zooms", "saturated grades"],
    agentNotes:
      "Synthesis base modeled on measured MKBHD numbers: ~7 cuts/min, median shot ~6s, ~50/50 talking head vs b-roll, a dense first 30s (10-14 cuts) then 2-5 cuts per 30s, one spec card (<=4 bullets), a 30-55s verdict at 70-90% of runtime.",
  },
  tech_review_entertainment: {
    id: "base-tech_review_entertainment",
    name: "Entertaining tech review (base)",
    category: "custom",
    archetype: "tech_review_entertainment",
    description: "Base for personality-led tech channels: cold-open joke, comparison charts, snap zooms and editor gags, sponsor segues.",
    tags: ["base", "tech", "review", "comedy", "comparison"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 480, typical: 840, max: 1500 },
    },
    pacing: {
      aslSec: 3.5,
      cutStyle: "jump",
      beatSync: "loose",
      maxSilenceMs: 200,
      keepFillers: false,
      hook: "Cold open with a joke, skit or bold claim and a hero product shot within 10s, then a short branded sting.",
      ending: "outro_card",
      punchIn: { scale: 1.3, perMin: 2, durFrames: 0 },
    },
    grade: {
      exposure: 0.05,
      contrast: 1.12,
      saturation: 1.1,
      vibrance: 0.1,
      temperature: 0,
      tint: 0,
      highlights: -0.08,
      shadows: -0.06,
      fade: 0,
      vignette: 0.1,
      grain: 0,
      look: "bright studio with dramatic product inserts",
    },
    palette: {
      background: "#141414",
      foreground: "#FFFFFF",
      accents: ["#FF5A1F", "#8A8A8A"],
      rule: "one brand accent for the product under test, gray for the rest",
    },
    typography: {
      title: {
        fontFamily: "Outfit",
        fontWeight: 700,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#FFFFFF",
        sizePctH: 7,
      },
      body: {
        fontFamily: "Outfit",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFFFFF",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Outfit",
        fontWeight: 700,
        textTransform: "uppercase",
        letterSpacing: 0.03,
        color: "#FF5A1F",
        sizePctH: 3.4,
      },
    },
    captions: {
      mode: "callout_only",
      style: {
        fontFamily: "Outfit",
        fontWeight: 600,
        fontSize: 46,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        emphasisColor: "#FF5A1F",
        textTransform: "none",
        background: { color: "rgba(0,0,0,0.75)", padding: 14, radius: 6 },
        animation: "fade",
        combineMs: 1400,
        maxWordsPerPage: 10,
      },
      yPct: 0.85,
    },
    transitions: {
      primary: "cut",
      secondary: ["slide", "zoom-in", "whip"],
      durationFrames: 6,
      frequency: 0.06,
      avoid: ["long static holds", "unlabeled charts"],
    },
    motion: {
      enter: "slide",
      exit: "slide",
      easing: "snappy",
      textAnimation: "pop",
      textUnit: "word",
      stagger: 2,
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 6,
    },
    overlays: ["bar-chart", "spec-card", "split-screen", "lower-third", "end-card", "subscribe-cta", "light-sweep"],
    sound: {
      music: "upbeat electronic beds",
      bpm: [100, 128],
      sfx: ["whoosh", "ding", "record-scratch", "impact"],
      sfxPerMin: 6,
      duckDb: 16,
    },
    signature: ["Cold-open joke or skit, then a sting", "Highlighted comparison/benchmark charts", "Snap zooms and editor text gags"],
    avoid: ["dry spec reading", "unlabeled data", "music over the host"],
    agentNotes:
      "Synthesis base. Choose light studio vs dark 'hero void' from the creator's look. Every comparison becomes a labeled chart with the tested product in the accent color; sponsor reads enter through a one-line segue; 1-3 snap zooms per minute on jokes.",
  },
  edu_animation: {
    id: "base-edu_animation",
    name: "Educational animation (base)",
    category: "custom",
    archetype: "edu_animation",
    description:
      "Base for animated explainers: one idea per scene, flat shapes with depth, continuous camera moves, dense micro-SFX under narration.",
    tags: ["base", "animation", "explainer", "motion graphics", "education"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 60, typical: 480, max: 1080 },
    },
    pacing: {
      aslSec: 5,
      cutStyle: "continuous",
      beatSync: "none",
      maxSilenceMs: 0,
      keepFillers: false,
      hook: "A striking visual and a question within the first 10s; one idea per scene after that.",
      ending: "outro_card",
    },
    grade: {
      exposure: 0,
      contrast: 1,
      saturation: 1.05,
      vibrance: 0.05,
      temperature: 0,
      tint: 0,
      highlights: 0,
      shadows: 0,
      fade: 0,
      vignette: 0.1,
      grain: 0.02,
      glow: 0.15,
      look: "flat vector with soft gradients and glows",
    },
    palette: {
      background: "#12142B",
      foreground: "#FFFFFF",
      accents: ["#FFB627", "#FF5E78", "#4CC9F0"],
      rule: "dark ground, at most two accents per scene",
    },
    typography: {
      title: {
        fontFamily: "Montserrat",
        fontWeight: 800,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#FFFFFF",
        sizePctH: 7,
      },
      body: {
        fontFamily: "Nunito",
        fontWeight: 600,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFFFFF",
        sizePctH: 3.6,
      },
      callout: {
        fontFamily: "Nunito",
        fontWeight: 800,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFB627",
        sizePctH: 9,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Nunito",
        fontWeight: 700,
        fontSize: 48,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "none",
        shadow: { color: "rgba(0,0,0,0.6)", blur: 8, x: 0, y: 2 },
        animation: "fade",
        combineMs: 1400,
        maxWordsPerPage: 8,
      },
      yPct: 0.87,
    },
    transitions: {
      primary: "zoom-in",
      secondary: ["push", "iris", "wipe"],
      durationFrames: 16,
      frequency: 0.5,
      avoid: ["static slides", "text paragraphs", "live-action stock"],
    },
    motion: {
      enter: "pop",
      exit: "zoom",
      easing: { type: "bezier", x1: 0.65, y1: 0, x2: 0.35, y2: 1 },
      textAnimation: "rise",
      textUnit: "word",
      stagger: 2,
      idleLoop: "float",
      kenBurns: false,
      shake: false,
      motionBlur: false,
      overshootPct: 8,
    },
    overlays: ["counter", "bar-chart", "arrow-callout", "map-route", "kinetic-title", "stat-grid"],
    sound: {
      music: "ambient / orchestral-electronic score under narration",
      bpm: [80, 115],
      sfx: ["pop", "whoosh", "swoosh", "tick", "sparkle"],
      sfxPerMin: 30,
      duckDb: 12,
    },
    signature: [
      "One idea per scene, explained visually",
      "Continuous camera moves and zoom-throughs between ideas",
      "Every element animates with a micro-SFX",
    ],
    avoid: ["static frames", "walls of text", "inconsistent illustration styles"],
    agentNotes:
      "Synthesis base. Script first (130-160 wpm), then storyboard one visual per sentence. Elements pop with 5-10% overshoot, idle-float 2-6px, 3-6 parallax layers. Transition by zooming into an element or morphing shapes. Override palette and type with the creator's brand.",
  },
  doc_essay: {
    id: "base-doc_essay",
    name: "Documentary essay (base)",
    category: "custom",
    archetype: "doc_essay",
    description:
      "Base for documentary/video-essay creators: question-led hook, evidence on screen (maps, archival, documents), filmic texture, J/L cuts.",
    tags: ["base", "documentary", "video essay", "explainer", "history"],
    format: {
      aspect: "16:9",
      fps: 24,
      durationSec: { min: 480, typical: 1080, max: 2400 },
    },
    pacing: {
      aslSec: 4.5,
      cutStyle: "mixed",
      beatSync: "loose",
      maxSilenceMs: 300,
      keepFillers: false,
      hook: "One question over the most intriguing piece of evidence (archival, map, document) within 20s, then a short teaser montage before the title.",
      ending: "fade",
    },
    grade: {
      exposure: 0,
      contrast: 1.06,
      saturation: 0.85,
      vibrance: -0.05,
      temperature: 0.04,
      tint: 0,
      highlights: -0.18,
      shadows: 0.04,
      fade: 0.06,
      lut: "matte-fade",
      vignette: 0.2,
      grain: 0.2,
      look: "muted filmic editorial",
    },
    palette: {
      background: "#F3EBDD",
      foreground: "#131313",
      accents: ["#FFF200", "#D62828"],
      rule: "muted paper/ink base, one highlight color for evidence",
    },
    typography: {
      title: {
        fontFamily: "Oswald",
        fontWeight: 700,
        textTransform: "uppercase",
        letterSpacing: 0.01,
        color: "#FFFFFF",
        shadow: { color: "rgba(0,0,0,0.45)", blur: 10, x: 0, y: 3 },
        sizePctH: 9,
      },
      body: {
        fontFamily: "Source Serif 4",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: -0.005,
        color: "#131313",
        sizePctH: 3.6,
      },
      callout: {
        fontFamily: "Roboto Mono",
        fontWeight: 500,
        textTransform: "uppercase",
        letterSpacing: 0.08,
        color: "#131313",
        sizePctH: 2.6,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Oswald",
        fontWeight: 600,
        fontSize: 56,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "uppercase",
        shadow: { color: "rgba(0,0,0,0.5)", blur: 8, x: 0, y: 2 },
        animation: "fade",
        combineMs: 1000,
        maxWordsPerPage: 6,
      },
      yPct: 0.82,
    },
    transitions: {
      primary: "cut",
      secondary: ["light-leak", "zoom-in", "dip-to-black"],
      durationFrames: 10,
      frequency: 0.12,
      avoid: ["glossy 3D graphics", "meme SFX", "unsourced visuals"],
    },
    motion: {
      enter: "mask-reveal",
      exit: "fade",
      easing: "ease-in-out",
      textAnimation: "mask-up",
      textUnit: "line",
      stagger: 4,
      idleLoop: "ken-burns",
      kenBurns: true,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["highlighter-sweep", "map-route", "paper-texture", "quote-card", "lower-third", "film-burn", "timeline"],
    sound: {
      music: "ambient documentary beds with pulses; risers into revelations",
      bpm: [70, 110],
      sfx: ["paper", "whoosh", "typewriter", "sub-drop"],
      sfxPerMin: 10,
      duckDb: 16,
    },
    signature: [
      "Question-led structure with evidence on screen",
      "Maps, documents and archival with highlights",
      "Grain and paper textures; J/L cuts",
    ],
    avoid: ["claims without sources on screen", "bouncy UI animation", "neon palettes"],
    agentNotes:
      "Synthesis base. Choose texture strength from the creator: Vox-like collage (12fps on twos, halftone cutouts), Johnny Harris-like film grain + marker, or Veritasium-like clean animation. Every claim gets a visual source (document, map, chart, archival). Keep music low and drop it for key statements.",
  },
  cinematic_vlog: {
    id: "base-cinematic_vlog",
    name: "Cinematic vlog (base)",
    category: "custom",
    archetype: "cinematic_vlog",
    description: "Base for cinematic vloggers: music-first editing, establishing shots, in-motion transitions, filmic grade, minimal text.",
    tags: ["base", "vlog", "cinematic", "travel", "music-driven"],
    format: {
      aspect: "16:9",
      fps: 24,
      durationSec: { min: 240, typical: 600, max: 1200 },
    },
    pacing: {
      aslSec: 2.6,
      cutStyle: "beat",
      beatSync: "loose",
      maxSilenceMs: 200,
      keepFillers: false,
      hook: "A striking establishing shot (timelapse, drone, golden hour) for 3-8s under the music, then the premise in one line.",
      ending: "fade",
    },
    grade: {
      exposure: 0.02,
      contrast: 1.15,
      saturation: 1.05,
      vibrance: 0.08,
      temperature: 0.06,
      tint: 0,
      highlights: -0.18,
      shadows: -0.08,
      fade: 0.02,
      lut: "golden-hour",
      vignette: 0.12,
      grain: 0.06,
      look: "warm filmic",
    },
    palette: {
      background: "#101010",
      foreground: "#FFFFFF",
      accents: ["#FFA552", "#FFFFFF"],
      rule: "color comes from the footage; plain white type",
    },
    typography: {
      title: {
        fontFamily: "Bebas Neue",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.08,
        color: "#FFFFFF",
        sizePctH: 8,
      },
      body: {
        fontFamily: "Inter",
        fontWeight: 600,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFFFFF",
        shadow: { color: "rgba(0,0,0,0.45)", blur: 6, x: 0, y: 2 },
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Oswald",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.1,
        color: "#FFA552",
        sizePctH: 4,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Inter",
        fontWeight: 600,
        fontSize: 48,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "none",
        shadow: { color: "rgba(0,0,0,0.6)", blur: 8, x: 0, y: 2 },
        animation: "fade",
        combineMs: 1200,
        maxWordsPerPage: 8,
      },
      yPct: 0.86,
    },
    transitions: {
      primary: "cut",
      secondary: ["whip", "light-leak", "zoom-in"],
      durationFrames: 6,
      frequency: 0.1,
      avoid: ["template transitions that don't hide the cut", "heavy graphics", "meme SFX"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "ease-in-out",
      textAnimation: "fade",
      textUnit: "line",
      stagger: 4,
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 0,
    },
    overlays: ["letterbox", "kinetic-title", "map-route"],
    sound: {
      music: "music-first: indie / electronic / cinematic instrumental",
      bpm: [85, 120],
      sfx: ["whoosh", "swoosh", "riser"],
      sfxPerMin: 6,
      duckDb: 12,
    },
    signature: ["Picture cut to a track chosen first", "Establishing timelapse/drone shots", "Whip pans and in-camera transitions"],
    avoid: ["dense captions", "stock-template motion graphics", "flat ungraded footage"],
    agentNotes:
      "Synthesis base. Pick the track first and cut montages on the beat (1.5-3s), talking segments 3-6s with jump cuts. Use real camera motion for transitions (whips, object wipes); add natural sound and foley under the music.",
  },
  chaotic_vlog: {
    id: "base-chaotic_vlog",
    name: "Chaotic vlog (base)",
    category: "custom",
    archetype: "chaotic_vlog",
    description:
      "Base for raw, relatable vlogs: kept mistakes, abrupt jump cuts, comedic zooms, plain commentary text, ironic stock music.",
    tags: ["base", "vlog", "chaotic", "relatable", "comedy"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 300, typical: 720, max: 1200 },
    },
    pacing: {
      aslSec: 2.5,
      cutStyle: "jump",
      beatSync: "none",
      maxSilenceMs: 0,
      keepFillers: true,
      hook: "Start mid-thought or on a blooper, with a sudden comedic zoom.",
      ending: "abrupt",
      punchIn: { scale: 1.8, perMin: 4, durFrames: 0 },
    },
    grade: {
      exposure: 0,
      contrast: 1,
      saturation: 1,
      vibrance: 0,
      temperature: 0.02,
      tint: 0,
      highlights: 0,
      shadows: 0,
      fade: 0,
      vignette: 0,
      grain: 0,
      look: "ungraded phone/webcam realism",
    },
    palette: {
      background: "#FFFFFF",
      foreground: "#111111",
      accents: ["#9EC5E8"],
      rule: "raw footage; plain white text",
    },
    typography: {
      title: {
        fontFamily: "Arimo",
        fontWeight: 700,
        textTransform: "lowercase",
        letterSpacing: 0,
        color: "#FFFFFF",
        shadow: { color: "rgba(0,0,0,0.5)", blur: 4, x: 1, y: 1 },
        sizePctH: 5,
      },
      body: {
        fontFamily: "Arimo",
        fontWeight: 700,
        textTransform: "lowercase",
        letterSpacing: 0,
        color: "#FFFFFF",
        shadow: { color: "rgba(0,0,0,0.5)", blur: 4, x: 1, y: 1 },
        sizePctH: 3.6,
      },
    },
    captions: {
      mode: "callout_only",
      style: {
        fontFamily: "Arimo",
        fontWeight: 700,
        fontSize: 54,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "lowercase",
        shadow: { color: "rgba(0,0,0,0.5)", blur: 4, x: 1, y: 1 },
        animation: "none",
        combineMs: 1500,
        maxWordsPerPage: 10,
      },
      yPct: 0.85,
    },
    transitions: {
      primary: "cut",
      secondary: ["zoom-in"],
      durationFrames: 2,
      frequency: 0.05,
      avoid: ["polished motion graphics", "cinematic grading", "removing mistakes"],
    },
    motion: {
      enter: "zoom",
      exit: "fade",
      easing: "linear",
      textAnimation: "none",
      textUnit: "line",
      stagger: 0,
      idleLoop: "shake",
      kenBurns: false,
      shake: true,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["kinetic-title", "kept blooper", "filter gag"],
    sound: {
      music: "ironic stock music for gags",
      bpm: [90, 120],
      sfx: ["record-scratch", "boing", "vine-boom"],
      sfxPerMin: 4,
      duckDb: 10,
    },
    signature: ["Mistakes and awkward silences kept on purpose", "Sudden comedic zoom-ins", "Plain commentary text"],
    avoid: ["polish", "smooth transitions", "color grading"],
    agentNotes:
      "Synthesis base. Edit for personality: leave the awkward pause, then undercut it with a zoom, a muffled-audio gag or an ironic music sting. Commentary text is lowercase and conversational, never a transcript.",
  },
  music_montage: {
    id: "base-music_montage",
    name: "Music montage (base)",
    category: "custom",
    archetype: "music_montage",
    description:
      "Base for beat-driven edits: every cut on the beat, speed ramps, flashes and shakes on hits, punchy grade, loopable ending.",
    tags: ["base", "montage", "beat sync", "edit", "music video"],
    format: {
      aspect: "9:16",
      fps: 30,
      durationSec: { min: 7, typical: 20, max: 120 },
    },
    pacing: {
      aslSec: 1,
      cutStyle: "beat",
      beatSync: "strict",
      maxSilenceMs: 0,
      keepFillers: false,
      hook: "The first cut lands on the first beat; the best shot sits on the first drop.",
      ending: "loop",
      punchIn: { scale: 1.2, perMin: 30, durFrames: 3 },
    },
    grade: {
      exposure: 0,
      contrast: 1.2,
      saturation: 1.15,
      vibrance: 0.1,
      temperature: 0,
      tint: 0,
      highlights: -0.05,
      shadows: -0.12,
      fade: 0,
      lut: "vivid-pop",
      vignette: 0.2,
      grain: 0.03,
      look: "punchy contrast",
    },
    palette: {
      background: "#000000",
      foreground: "#FFFFFF",
      accents: ["#FFFFFF"],
      rule: "the footage carries the color",
    },
    typography: {
      title: {
        fontFamily: "Montserrat",
        fontWeight: 800,
        textTransform: "uppercase",
        letterSpacing: 0.04,
        color: "#FFFFFF",
        sizePctH: 4,
      },
      body: {
        fontFamily: "Montserrat",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.06,
        color: "#FFFFFF",
        sizePctH: 2.6,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Montserrat",
        fontWeight: 800,
        fontSize: 56,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "uppercase",
        animation: "pop",
        combineMs: 400,
        maxWordsPerPage: 3,
      },
      yPct: 0.5,
    },
    transitions: {
      primary: "cut",
      secondary: ["flash", "zoom-in", "whip", "glitch"],
      durationFrames: 3,
      frequency: 0.35,
      avoid: ["cuts off the beat", "dissolves", "long holds"],
    },
    motion: {
      enter: "zoom",
      exit: "zoom",
      easing: "snappy",
      textAnimation: "fade",
      textUnit: "word",
      stagger: 2,
      kenBurns: false,
      shake: true,
      motionBlur: true,
      overshootPct: 0,
    },
    overlays: ["kinetic-title", "letterbox"],
    sound: {
      music: "the track drives everything",
      bpm: [120, 160],
      sfx: ["whoosh", "impact", "bass-hit"],
      sfxPerMin: 25,
      duckDb: 0,
    },
    signature: ["Every cut on a beat", "Speed ramps landing slow motion on the drop", "Flash/shake/zoom accents on hits"],
    avoid: ["voiceover", "cuts between beats", "static shots"],
    agentNotes:
      "Synthesis base. Beat-map first. Cut on strong beats; accent weak beats with zooms/shakes instead of extra cuts. Shakes 2-3 frames, flashes 1-2 frames. Choose 16:9 for travel/gaming YouTube montages and 9:16 for social edits.",
  },
  brand_film: {
    id: "base-brand_film",
    name: "Brand film (base)",
    category: "custom",
    archetype: "brand_film",
    description:
      "Base for brand and product films: one idea per frame, huge restrained type, slow precise camera, tactile sound, logo sting.",
    tags: ["base", "brand", "product film", "commercial", "premium"],
    format: {
      aspect: "16:9",
      fps: 24,
      durationSec: { min: 15, typical: 60, max: 120 },
    },
    pacing: {
      aslSec: 2.5,
      cutStyle: "beat",
      beatSync: "loose",
      maxSilenceMs: 0,
      keepFillers: false,
      hook: "An abstract macro or emotional close-up within 3s; the brand idea in one line by 5s.",
      ending: "logo_sting",
    },
    grade: {
      exposure: 0,
      contrast: 1.1,
      saturation: 1,
      vibrance: 0,
      temperature: 0,
      tint: 0,
      highlights: -0.25,
      shadows: -0.05,
      fade: 0,
      vignette: 0.05,
      grain: 0,
      look: "clean premium with controlled highlights",
    },
    palette: {
      background: "#000000",
      foreground: "#F5F5F7",
      accents: ["#F5F5F7"],
      rule: "neutral void + the product's own color",
    },
    typography: {
      title: {
        fontFamily: "Inter Tight",
        fontWeight: 600,
        textTransform: "none",
        letterSpacing: -0.03,
        lineHeight: 1.05,
        color: "#F5F5F7",
        sizePctH: 11,
      },
      body: {
        fontFamily: "Inter",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#A1A1A6",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Inter Tight",
        fontWeight: 700,
        textTransform: "none",
        letterSpacing: -0.04,
        color: "#F5F5F7",
        sizePctH: 16,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Inter",
        fontWeight: 500,
        fontSize: 44,
        color: "#F5F5F7",
        activeColor: "#F5F5F7",
        textTransform: "none",
        animation: "fade",
        combineMs: 1500,
        maxWordsPerPage: 10,
      },
      yPct: 0.88,
    },
    transitions: {
      primary: "cut",
      secondary: ["fade", "dip-to-black"],
      durationFrames: 12,
      frequency: 0.12,
      avoid: ["particles and lens flares", "camera shake", "busy layouts"],
    },
    motion: {
      enter: "rise-blur",
      exit: "blur",
      easing: "apple",
      textAnimation: "rise-blur",
      textUnit: "line",
      stagger: 3,
      idleLoop: "drift",
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 5,
    },
    overlays: ["logo-reveal", "kinetic-title", "light-sweep", "device-frame", "end-card"],
    sound: {
      music: "a single strong track cut on the beat, plus tactile foley",
      bpm: [90, 128],
      sfx: ["whoosh", "click", "impact", "sub-drop"],
      sfxPerMin: 8,
      duckDb: 14,
    },
    signature: ["One idea per frame with huge restrained type", "Slow, precise camera on the product or people", "Logo sting ending"],
    avoid: ["clutter", "cheap effects", "more than one accent"],
    agentNotes:
      "Synthesis base. Decide the register from the brand: pristine/minimal (tech) vs gritty/emotional (sport, fashion). Keep layouts sparse, overlap eased keyframes, sync cuts and foley to the music, end on the logo with one line.",
  },
  saas_launch: {
    id: "base-saas_launch",
    name: "SaaS launch (base)",
    category: "custom",
    archetype: "saas_launch",
    description:
      "Base for product launch videos: product on screen within 3s, real UI as components, dark background + one accent, no-bounce motion, CTA end.",
    tags: ["base", "saas", "launch", "product demo", "startup", "ui"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 15, typical: 30, max: 60 },
    },
    pacing: {
      aslSec: 2,
      cutStyle: "beat",
      beatSync: "loose",
      maxSilenceMs: 0,
      keepFillers: false,
      hook: "The product (or one unmistakable UI artifact) is on screen within 3s with a <=8-word headline.",
      ending: "cta",
    },
    grade: {
      exposure: 0,
      contrast: 1.05,
      saturation: 1,
      vibrance: 0,
      temperature: 0,
      tint: 0,
      highlights: 0,
      shadows: 0,
      fade: 0,
      vignette: 0.15,
      grain: 0.04,
      glow: 0.2,
      look: "dark canvas with one soft accent glow and subtle noise",
    },
    palette: {
      background: "#0A0A0B",
      foreground: "#F5F5F5",
      accents: ["#5B8CFF"],
      rule: "dark background + exactly one accent; never a purple-to-blue gradient wash",
    },
    typography: {
      title: {
        fontFamily: "Inter",
        fontWeight: 600,
        textTransform: "none",
        letterSpacing: -0.03,
        lineHeight: 1.1,
        color: "#F5F5F5",
        sizePctH: 7.5,
      },
      body: {
        fontFamily: "Inter",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#A3A3A3",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Geist Mono",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: 0,
        color: "#F5F5F5",
        sizePctH: 2.8,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Inter",
        fontWeight: 600,
        fontSize: 52,
        color: "#F5F5F5",
        activeColor: "#5B8CFF",
        textTransform: "none",
        animation: "fade",
        combineMs: 800,
        maxWordsPerPage: 5,
      },
      yPct: 0.84,
    },
    transitions: {
      primary: "cut",
      secondary: ["blur", "push", "zoom-in"],
      durationFrames: 8,
      frequency: 0.3,
      avoid: ["bouncy UI chrome", "invented UI", "static frames over 2s", "the same transition twice in a row"],
    },
    motion: {
      enter: "rise-blur",
      exit: "blur",
      easing: { type: "spring", damping: 26, stiffness: 220, mass: 1 },
      textAnimation: "mask-up",
      textUnit: "word",
      stagger: 1.5,
      idleLoop: "drift",
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 0,
    },
    overlays: ["browser-window", "device-frame", "cursor-click", "glow-orbs", "grid-background", "stat-grid", "logo-reveal", "end-card"],
    sound: {
      music: "minimal electronic underscore",
      bpm: [100, 128],
      sfx: ["click", "tick", "whoosh"],
      sfxPerMin: 14,
      duckDb: 12,
    },
    signature: [
      "Product visible within 3s",
      "Real UI rebuilt as components on 3D-tilted planes",
      "Animated cursor with zoom-to-click",
      "No-bounce springs and ~50ms staggers",
    ],
    avoid: ["fake UI", "purple-to-blue gradient backgrounds", "everything fading in", "nothing moving in the first seconds"],
    agentNotes:
      "Research: product visible in the first 3s, real UI rebuilt as components, dark background + one accent, no-bounce springs, ~50ms staggers, 3D tilt, animated cursor with zoom-to-click, 15-37s total, CTA end. 30s structure: hook 15% / reveal 15% / showcase 45% / climax 15% / close 10%. Primary motions 400-600ms, secondary 300-500ms, scene transitions 200-400ms. Burn captions into the feed cut for muted autoplay.",
  },
  trailer: {
    id: "base-trailer",
    name: "Trailer (base)",
    category: "custom",
    archetype: "trailer",
    description:
      "Base for film/game/product trailers: three-act build, title cards on hits, drones -> pulses -> silence -> smash cut, letterboxed film grade.",
    tags: ["base", "trailer", "cinematic", "teaser", "title cards"],
    format: {
      aspect: "16:9",
      fps: 24,
      durationSec: { min: 30, typical: 120, max: 150 },
      letterbox: 2.39,
    },
    pacing: {
      aslSec: 2.5,
      cutStyle: "mixed",
      beatSync: "loose",
      maxSilenceMs: 0,
      keepFillers: true,
      hook: "Cold open mid-scene with one intriguing line; no logos first.",
      ending: "outro_card",
    },
    grade: {
      exposure: -0.05,
      contrast: 1.1,
      saturation: 0.85,
      vibrance: -0.05,
      temperature: 0,
      tint: 0,
      highlights: -0.2,
      shadows: -0.02,
      fade: 0.04,
      lut: "film-print",
      vignette: 0.15,
      grain: 0.2,
      look: "cinematic print film",
    },
    palette: {
      background: "#000000",
      foreground: "#F2EFEA",
      accents: ["#C9B37E"],
      rule: "black cards, off-white type",
    },
    typography: {
      title: {
        fontFamily: "Cinzel",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.15,
        color: "#F2EFEA",
        sizePctH: 6,
      },
      body: {
        fontFamily: "Inter",
        fontWeight: 500,
        textTransform: "uppercase",
        letterSpacing: 0.25,
        color: "#F2EFEA",
        sizePctH: 2.8,
      },
      callout: {
        fontFamily: "EB Garamond",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: 0.02,
        color: "#F2EFEA",
        italic: true,
        sizePctH: 4,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Inter",
        fontWeight: 500,
        fontSize: 40,
        color: "#F2EFEA",
        activeColor: "#F2EFEA",
        textTransform: "none",
        animation: "fade",
        combineMs: 1500,
        maxWordsPerPage: 10,
      },
      yPct: 0.86,
    },
    transitions: {
      primary: "cut",
      secondary: ["dip-to-black", "flash"],
      durationFrames: 6,
      frequency: 0.3,
      avoid: ["revealing the whole plot", "playful transitions", "bright pop grades"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "ease-in-out",
      textAnimation: "fade",
      textUnit: "line",
      stagger: 6,
      idleLoop: "drift",
      kenBurns: true,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["letterbox", "quote-card", "kinetic-title", "end-card"],
    sound: {
      music: "drones -> rhythmic pulses -> full score; silence before the final hit",
      bpm: [70, 120],
      sfx: ["braam", "impact", "riser", "sub-drop", "whoosh"],
      sfxPerMin: 10,
      duckDb: 10,
    },
    signature: ["Three-act build with accelerating cuts", "Title cards landing on hits", "A silence right before the final smash cut"],
    avoid: ["plot recaps", "flat audio dynamics", "logo-first openings"],
    agentNotes:
      "Synthesis base. Act 1 (4-8s shots, drone, setup line) -> act 2 (pulses, 2-3s shots, cards on hits) -> act 3 (0.3-1s strobe montage, silence, smash cut) -> title -> stinger -> date. Mute about a third of the sound design on the first pass; contrast beats loudness.",
  },
  auteur_look: {
    id: "base-auteur_look",
    name: "Auteur film look (base)",
    category: "custom",
    archetype: "auteur_look",
    description:
      "Base for director-style looks: deliberate composition, signature typeface on title cards, a specific palette and camera grammar, film grain.",
    tags: ["base", "director", "film look", "auteur", "cinematic"],
    format: {
      aspect: "16:9",
      fps: 24,
      durationSec: { min: 15, typical: 60, max: 180 },
      letterbox: 1.85,
    },
    pacing: {
      aslSec: 4.5,
      cutStyle: "hard",
      beatSync: "loose",
      maxSilenceMs: 0,
      keepFillers: true,
      hook: "A composed establishing tableau plus a title card in the director's typeface.",
      ending: "outro_card",
    },
    grade: {
      exposure: 0,
      contrast: 0.98,
      saturation: 0.95,
      vibrance: 0,
      temperature: 0.06,
      tint: 0,
      highlights: -0.15,
      shadows: 0.05,
      fade: 0.05,
      lut: "film-print",
      vignette: 0.05,
      grain: 0.15,
      look: "35mm print film",
    },
    palette: {
      background: "#1E1B18",
      foreground: "#F4EDE1",
      accents: ["#C1554D", "#F2D06B", "#9DC3C2"],
      rule: "3-5 signature colors used consistently",
    },
    typography: {
      title: {
        fontFamily: "Jost",
        originalFont: "Futura",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.08,
        color: "#F4EDE1",
        sizePctH: 6,
      },
      body: {
        fontFamily: "EB Garamond",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: 0.01,
        color: "#F4EDE1",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Courier Prime",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: 0,
        color: "#F4EDE1",
        sizePctH: 3.2,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Jost",
        fontWeight: 500,
        fontSize: 44,
        color: "#F4EDE1",
        activeColor: "#F4EDE1",
        textTransform: "uppercase",
        animation: "typewriter",
        combineMs: 1500,
        maxWordsPerPage: 8,
        letterSpacing: 0.06,
      },
      yPct: 0.88,
    },
    transitions: {
      primary: "cut",
      secondary: ["whip", "dip-to-black"],
      durationFrames: 8,
      frequency: 0.1,
      avoid: ["generic template transitions", "inconsistent framing", "modern UI graphics"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "ease-in-out",
      textAnimation: "typewriter",
      textUnit: "char",
      stagger: 1,
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 0,
    },
    overlays: ["chapter-card", "letterbox", "kinetic-title"],
    sound: {
      music: "score-forward: the director's signature instrumentation or needle drops",
      bpm: [80, 130],
      sfx: ["whoosh", "typewriter"],
      sfxPerMin: 3,
      duckDb: 12,
    },
    signature: [
      "Consistent composition rule (symmetry, one-point perspective, or off-center)",
      "Signature typeface on chapter/title cards",
      "A fixed 3-5 color palette and film grain",
    ],
    avoid: ["mixing visual grammars", "default fonts", "handheld chaos unless it is the signature"],
    agentNotes:
      "Synthesis base for 'make it look like <director>'. Override: composition rule (symmetry for Kubrick/Anderson), palette (neon step-printing for Wong Kar-wai, green-yellow desaturation for Fincher), title-card typeface and chapter structure (Tarantino), camera grammar (whips, crash zooms, long takes) and music register.",
  },
  retro_texture: {
    id: "base-retro_texture",
    name: "Retro texture (base)",
    category: "custom",
    archetype: "retro_texture",
    description:
      "Base for analog-era looks (VHS, film, lo-fi): lifted blacks, grain/noise, chroma bleed, period type, tape or vinyl audio texture.",
    tags: ["base", "retro", "analog", "vintage", "texture"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 10, typical: 45, max: 300 },
    },
    pacing: {
      aslSec: 4,
      cutStyle: "hard",
      beatSync: "none",
      maxSilenceMs: 0,
      keepFillers: true,
      hook: "Open with an analog artifact (tape glitch, film leader, a timestamp) straight into the first shot.",
      ending: "abrupt",
    },
    grade: {
      exposure: 0,
      contrast: 0.9,
      saturation: 0.95,
      vibrance: 0,
      temperature: 0.08,
      tint: 0.03,
      highlights: -0.05,
      shadows: 0.06,
      fade: 0.12,
      lut: "matte-fade",
      vignette: 0.25,
      grain: 0.3,
      chromaticAberration: 2,
      glow: 0.15,
      look: "analog: lifted blacks, warm, soft, textured",
    },
    palette: {
      background: "#1C1A24",
      foreground: "#F3E9DC",
      accents: ["#FFB000", "#E8A87C", "#8E7DBE"],
      rule: "period-appropriate warm/muted colors",
    },
    typography: {
      title: {
        fontFamily: "VT323",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.04,
        color: "#F3E9DC",
        shadow: { color: "rgba(255,255,255,0.4)", blur: 6, x: 0, y: 0 },
        sizePctH: 7,
      },
      body: {
        fontFamily: "Space Mono",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: 0.02,
        color: "#F3E9DC",
        sizePctH: 3,
      },
      callout: {
        fontFamily: "Courier Prime",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.04,
        color: "#FFB000",
        sizePctH: 3.4,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Space Mono",
        fontWeight: 400,
        fontSize: 44,
        color: "#F3E9DC",
        activeColor: "#F3E9DC",
        textTransform: "none",
        animation: "typewriter",
        combineMs: 1200,
        maxWordsPerPage: 8,
      },
      yPct: 0.86,
    },
    transitions: {
      primary: "cut",
      secondary: ["glitch", "light-leak", "dip-to-black"],
      durationFrames: 5,
      frequency: 0.3,
      avoid: ["crisp digital sharpness", "modern glossy UI", "clean digital blacks"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "linear",
      textAnimation: "typewriter",
      textUnit: "char",
      stagger: 1,
      idleLoop: "wiggle",
      kenBurns: false,
      shake: true,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["vhs-overlay", "film-burn", "letterbox", "paper-texture"],
    sound: {
      music: "lo-fi / tape-saturated / vinyl-crackle music",
      bpm: [70, 110],
      sfx: ["glitch", "click", "tick"],
      sfxPerMin: 4,
      duckDb: 10,
    },
    signature: ["Lifted blacks with grain/noise", "Period typography (VCR, typewriter, mono)", "Analog artifacts between clips"],
    avoid: ["4K crispness", "modern sans titles", "smooth digital motion"],
    agentNotes:
      "Synthesis base. Pick the era: VHS (4:3 pillarbox, chroma bleed, scanlines, tracking bands, OSD text; LUT 'vhs'), 16mm/Super-8 (gate weave, film burns, 18fps feel; LUT 'film-print'), or lo-fi (warm faded, low-opacity noise; LUT 'matte-fade'). Match audio texture: tape hiss, vinyl crackle, low-pass.",
  },
  event_or_property: {
    id: "base-event_or_property",
    name: "Event / property film (base)",
    category: "custom",
    archetype: "event_or_property",
    description:
      "Base for weddings, events and property tours: smooth gimbal and drone shots, bright soft grade, elegant titles, gentle dissolves.",
    tags: ["base", "event", "wedding", "real estate", "cinematic"],
    format: {
      aspect: "16:9",
      fps: 24,
      durationSec: { min: 30, typical: 180, max: 360 },
    },
    pacing: {
      aslSec: 3.2,
      cutStyle: "mixed",
      beatSync: "loose",
      maxSilenceMs: 0,
      keepFillers: true,
      hook: "The most beautiful hero shot (venue or exterior at golden hour, or a drone reveal) with the key title (names or address) within 5s.",
      ending: "outro_card",
    },
    grade: {
      exposure: 0.1,
      contrast: 0.98,
      saturation: 0.95,
      vibrance: 0.05,
      temperature: 0.06,
      tint: 0,
      highlights: -0.3,
      shadows: 0.1,
      fade: 0.05,
      lut: "portra",
      vignette: 0.05,
      grain: 0.05,
      look: "bright, soft and flattering",
    },
    palette: {
      background: "#F6F0E8",
      foreground: "#2E2A27",
      accents: ["#C9B79C", "#FFFFFF"],
      rule: "soft neutrals; white elegant type",
    },
    typography: {
      title: {
        fontFamily: "Cormorant Garamond",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.15,
        color: "#FFFFFF",
        sizePctH: 6,
      },
      body: {
        fontFamily: "Lato",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: 0.02,
        color: "#FFFFFF",
        sizePctH: 3,
      },
      callout: {
        fontFamily: "Montserrat",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.08,
        color: "#C9B79C",
        sizePctH: 3.2,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Lato",
        fontWeight: 700,
        fontSize: 44,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "none",
        shadow: { color: "rgba(0,0,0,0.35)", blur: 8, x: 0, y: 2 },
        animation: "fade",
        combineMs: 1500,
        maxWordsPerPage: 10,
      },
      yPct: 0.88,
    },
    transitions: {
      primary: "cut",
      secondary: ["fade", "dip-to-white"],
      durationFrames: 14,
      frequency: 0.3,
      avoid: ["whips, glitches or flashes", "shaky handheld", "script fonts on property info"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "gentle",
      textAnimation: "fade",
      textUnit: "line",
      stagger: 6,
      idleLoop: "drift",
      kenBurns: true,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["lower-third", "kinetic-title", "map-route", "end-card", "letterbox"],
    sound: {
      music: "piano / strings / ambient, or 80-120 BPM modern pop",
      bpm: [70, 120],
      sfx: [],
      sfxPerMin: 0,
      duckDb: 12,
    },
    signature: ["Smooth gimbal glides and drone reveals", "Bright, soft, flattering grade", "Elegant titles and gentle dissolves"],
    avoid: ["hard flash transitions", "busy graphics", "harsh contrast"],
    agentNotes:
      "Synthesis base. Weddings: structure by emotion with vows/speeches as voiceover, slow motion, 2.39 letterbox. Property: exterior -> entry -> living -> kitchen -> bedrooms -> baths -> outdoor -> aerial, 3-5s wides, 2-3s details, spec lower thirds, no script fonts or drop shadows.",
  },
  stream_clip: {
    id: "base-stream_clip",
    name: "Stream clip (base)",
    category: "custom",
    archetype: "stream_clip",
    description:
      "Base for livestream highlights: vertical facecam/gameplay stack, word-by-word captions on the seam, meme-SFX zooms, zero setup.",
    tags: ["base", "stream", "gaming", "clips", "shorts", "facecam"],
    format: {
      aspect: "9:16",
      fps: 30,
      durationSec: { min: 10, typical: 30, max: 60 },
    },
    pacing: {
      aslSec: 2,
      cutStyle: "jump",
      beatSync: "none",
      maxSilenceMs: 200,
      keepFillers: true,
      hook: "Start ON the funniest line or reaction; no setup or context card.",
      ending: "loop",
      punchIn: { scale: 1.5, perMin: 6, durFrames: 2 },
    },
    grade: {
      exposure: 0.05,
      contrast: 1.05,
      saturation: 1.05,
      vibrance: 0.05,
      temperature: 0,
      tint: 0,
      highlights: 0,
      shadows: 0,
      fade: 0,
      vignette: 0,
      grain: 0,
      look: "as-streamed",
    },
    palette: {
      background: "#000000",
      foreground: "#FFFFFF",
      accents: ["#FFE14D", "#9146FF"],
      rule: "white captions + yellow active word",
    },
    typography: {
      title: {
        fontFamily: "Montserrat",
        fontWeight: 900,
        textTransform: "uppercase",
        letterSpacing: 0,
        color: "#FFFFFF",
        stroke: { color: "#000000", width: 8 },
        sizePctH: 5,
      },
      body: {
        fontFamily: "Montserrat",
        fontWeight: 700,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFFFFF",
        stroke: { color: "#000000", width: 4 },
        sizePctH: 2.8,
      },
    },
    captions: {
      mode: "word_by_word",
      style: {
        fontFamily: "Montserrat",
        fontWeight: 900,
        fontSize: 84,
        color: "#FFFFFF",
        activeColor: "#FFE14D",
        textTransform: "uppercase",
        stroke: { color: "#000000", width: 8 },
        animation: "pop",
        combineMs: 350,
        maxWordsPerPage: 3,
      },
      yPct: 0.44,
    },
    transitions: {
      primary: "cut",
      secondary: ["zoom-in", "glitch"],
      durationFrames: 3,
      frequency: 0.05,
      avoid: ["intros", "dead air", "letterboxed gameplay with empty bars"],
    },
    motion: {
      enter: "pop",
      exit: "fade",
      easing: "bouncy",
      textAnimation: "pop",
      textUnit: "word",
      stagger: 1,
      kenBurns: false,
      shake: true,
      motionBlur: false,
      overshootPct: 20,
    },
    overlays: ["split-screen", "emoji-pop", "social-post"],
    sound: {
      music: "none or quiet lo-fi under gameplay",
      bpm: [80, 110],
      sfx: ["vine-boom", "record-scratch", "boing"],
      sfxPerMin: 6,
      duckDb: 12,
    },
    signature: ["Facecam over gameplay in 9:16", "Captions on the seam", "Meme-SFX snap zooms on reactions"],
    avoid: ["setup before the joke", "small captions", "silence"],
    agentNotes:
      "Synthesis base. Facecam 35-45% of height on top, gameplay below (or full gameplay + PiP). Remove dead air, keep the laugh, add 1.3-2.0x zooms on reactions with a meme SFX, and make the end loop back into the start.",
  },
  minimal_essay: {
    id: "base-minimal_essay",
    name: "Minimal essay (base)",
    category: "custom",
    archetype: "minimal_essay",
    description:
      "Base for calm voiceover essays and quote reels: muted near-monochrome footage, small centered text, slow pushes, ambient music.",
    tags: ["base", "minimal", "essay", "quotes", "philosophy", "reels"],
    format: {
      aspect: "9:16",
      fps: 30,
      durationSec: { min: 20, typical: 60, max: 600 },
    },
    pacing: {
      aslSec: 4,
      cutStyle: "hard",
      beatSync: "loose",
      maxSilenceMs: 250,
      keepFillers: false,
      hook: "One provocative sentence on frame 0, centered, over a slow-moving shot.",
      ending: "fade",
    },
    grade: {
      exposure: -0.05,
      contrast: 1.2,
      saturation: 0.4,
      vibrance: -0.1,
      temperature: 0,
      tint: 0,
      highlights: -0.1,
      shadows: -0.15,
      fade: 0,
      vignette: 0.3,
      grain: 0.15,
      glow: 0.15,
      look: "muted near-monochrome with grain and soft bloom",
    },
    palette: {
      background: "#000000",
      foreground: "#FFFFFF",
      accents: ["#BDBDBD"],
      rule: "near-monochrome; hierarchy through size and opacity",
    },
    typography: {
      title: {
        fontFamily: "Cormorant Garamond",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: 0.01,
        color: "#FFFFFF",
        sizePctH: 3.6,
      },
      body: {
        fontFamily: "Inter",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: 0.01,
        color: "#EDEDED",
        sizePctH: 2.6,
      },
      callout: {
        fontFamily: "Inter",
        fontWeight: 500,
        textTransform: "lowercase",
        letterSpacing: 0.04,
        color: "#FFFFFF",
        sizePctH: 2.4,
      },
    },
    captions: {
      mode: "phrase",
      style: {
        fontFamily: "Inter",
        fontWeight: 500,
        fontSize: 50,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "none",
        shadow: { color: "rgba(0,0,0,0.6)", blur: 12, x: 0, y: 2 },
        animation: "fade",
        combineMs: 1600,
        maxWordsPerPage: 8,
        lineHeight: 1.3,
      },
      yPct: 0.5,
    },
    transitions: {
      primary: "cut",
      secondary: ["fade", "dip-to-black"],
      durationFrames: 15,
      frequency: 0.3,
      avoid: ["bright colors", "fast cutting", "bouncy motion", "emoji"],
    },
    motion: {
      enter: "blur",
      exit: "fade",
      easing: "gentle",
      textAnimation: "rise-blur",
      textUnit: "line",
      stagger: 6,
      idleLoop: "ken-burns",
      kenBurns: true,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["quote-card", "kinetic-title"],
    sound: {
      music: "ambient pads / sparse piano",
      bpm: [60, 90],
      sfx: ["whoosh", "sub-drop"],
      sfxPerMin: 2,
      duckDb: 14,
    },
    signature: ["Muted near-monochrome footage", "Small centered sentence-case text", "Slow pushes under a calm voiceover"],
    avoid: ["saturated color", "stroked caps captions", "meme editing"],
    agentNotes:
      "Synthesis base. Fully desaturate for a Dan Koe-like look, or keep 30-50% saturation for softer essay channels. Text: 3-8 word lines that blur/fade in on the phrase. Footage: statues, nature, cities, silhouettes, 3-6s holds with 1.00->1.06 pushes.",
  },
};
