import type { StyleDNA } from "../schema";

/**
 * Brand film / launch-video styles. "Inspired by" references only — Reframer
 * presets never imply affiliation with, or endorsement by, these companies.
 */
export const BRAND_STYLES: StyleDNA[] = [
  {
    id: "apple-keynote",
    name: "Apple keynote",
    category: "brand",
    archetype: "brand_film",
    description:
      "Apple-style product film / keynote graphics: product floating in a pure void, huge tightly tracked type, one slow precise camera.",
    inspiredBy: "Apple product films and keynote motion graphics",
    tags: ["apple", "product film", "keynote", "wwdc", "launch", "premium", "minimal", "product reveal"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 30, typical: 90, max: 150 },
    },
    pacing: {
      aslSec: 2.5,
      cutStyle: "beat",
      beatSync: "loose",
      maxSilenceMs: 300,
      keepFillers: false,
      hook: "0-3s: an abstract macro detail (light raking across an edge or material), then the product silhouette reveal; one huge word or line of type within 5s.",
      ending: "logo_sting",
    },
    grade: {
      exposure: 0,
      contrast: 1.12,
      saturation: 1,
      vibrance: 0,
      temperature: 0,
      tint: 0,
      highlights: -0.3,
      shadows: -0.05,
      fade: 0,
      vignette: 0,
      grain: 0,
      look: "pristine studio: pure black or white voids, controlled speculars, no texture",
    },
    palette: {
      background: "#000000",
      foreground: "#F5F5F7",
      accents: ["#2997FF", "#BF5AF2", "#FF9F0A"],
      rule: "black or white void; the product's color is the only color, gradients live inside hero words",
    },
    typography: {
      title: {
        fontFamily: "Inter Tight",
        originalFont: "SF Pro Display",
        fontWeight: 600,
        textTransform: "none",
        letterSpacing: -0.035,
        lineHeight: 1.05,
        color: "#F5F5F7",
        gradient: ["#FF9F0A", "#BF5AF2", "#2997FF"],
        sizePctH: 13,
      },
      body: {
        fontFamily: "Inter",
        originalFont: "SF Pro Text",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: -0.01,
        lineHeight: 1.3,
        color: "#A1A1A6",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Inter Tight",
        originalFont: "SF Pro Display",
        fontWeight: 700,
        textTransform: "none",
        letterSpacing: -0.04,
        color: "#F5F5F7",
        sizePctH: 18,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Inter",
        fontWeight: 500,
        fontSize: 44,
        color: "#F5F5F7",
        activeColor: "#F5F5F7",
        textTransform: "none",
        animation: "fade",
        combineMs: 1500,
        maxWordsPerPage: 10,
        letterSpacing: -0.01,
      },
      yPct: 0.88,
    },
    transitions: {
      primary: "cut",
      secondary: ["fade", "dip-to-black", "zoom-in"],
      durationFrames: 15,
      frequency: 0.15,
      avoid: ["whip, glitch, flash or spin transitions", "light leaks and lens flares", "particles", "camera shake"],
    },
    motion: {
      enter: "rise-blur",
      exit: "blur",
      easing: "apple",
      textAnimation: "rise-blur",
      textUnit: "line",
      stagger: 3,
      idleLoop: "drift",
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 5,
    },
    overlays: ["device-frame", "light-sweep", "logo-reveal", "stat-grid", "line-chart", "kinetic-title"],
    sound: {
      music: "product film: punchy licensed-feel electronic/pop cut on the beat; keynote: ambient beds under transitions, dry under speech",
      bpm: [100, 128],
      sfx: ["whoosh", "click", "tick", "sub-drop"],
      sfxPerMin: 6,
      duckDb: 18,
    },
    signature: [
      "Product floating in a pure black or white void with controlled specular highlights",
      "Huge, tightly tracked SF-style headlines (1-5 words), hero words in a gradient",
      "One continuous, slow, precise camera: orbits ~5-15deg/s, gentle 1.00->1.05 push-ins",
      "Text reveals = fade + 20px rise + blur 8->0 over 500-700ms, lines staggered 80-120ms",
      "Exaggerated tactile foley (clicks, magnetic snaps, air) on a beat-cut track",
    ],
    avoid: [
      "particles, lens flares, light leaks or shake",
      "bouncy UI chrome (more than 5-8% overshoot)",
      "busy layouts or more than one idea per frame",
      "stock footage or invented UI",
      "a centered headline on a purple-to-blue gradient",
    ],
    agentNotes:
      "Research consensus: one continuous camera, huge tightly tracked type, sparse layout, eased overlapping keyframes; no particles/flares/shake. Structure for a product film: macro tease -> silhouette reveal -> 3-5 feature beats (one idea each: huge numeral or 1-5 word headline + product angle) -> hero orbit -> logo. Exploded views: separate parts over 600-900ms, staggered. Keynote segments: presenter shots held 5-15s with slow dolly, full-screen slides with one huge number and a minimal single-accent chart. Real UI only (device frames); render UI-heavy segments at 60fps if possible.",
  },
  {
    id: "shot-on-iphone",
    name: "Shot on iPhone",
    category: "brand",
    archetype: "brand_film",
    description: "Real-world footage as the hero: natural grade, zero VFX, a tiny 'Shot on iPhone' credit and a logo end card.",
    inspiredBy: "Apple 'Shot on iPhone' campaign",
    tags: ["apple", "shot on iphone", "ugc", "documentary", "natural", "brand campaign"],
    format: {
      aspect: "16:9",
      fps: 24,
      durationSec: { min: 15, typical: 60, max: 90 },
    },
    pacing: {
      aslSec: 3,
      cutStyle: "beat",
      beatSync: "loose",
      maxSilenceMs: 0,
      keepFillers: true,
      hook: "Open on the single most striking real shot - no title, no text; the camera credit appears small in a corner.",
      ending: "logo_sting",
    },
    grade: {
      exposure: 0,
      contrast: 1.05,
      saturation: 1,
      vibrance: 0.05,
      temperature: 0,
      tint: 0,
      highlights: -0.15,
      shadows: 0.03,
      fade: 0,
      vignette: 0,
      grain: 0,
      look: "as-shot natural color; the footage speaks for itself",
    },
    palette: {
      background: "#000000",
      foreground: "#FFFFFF",
      accents: ["#FFFFFF"],
      rule: "no brand colors; white text only",
    },
    typography: {
      title: {
        fontFamily: "Inter",
        originalFont: "SF Pro Display",
        fontWeight: 600,
        textTransform: "none",
        letterSpacing: -0.02,
        color: "#FFFFFF",
        sizePctH: 6,
      },
      body: {
        fontFamily: "Inter",
        originalFont: "SF Pro Text",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFFFFF",
        sizePctH: 2.6,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Inter",
        fontWeight: 500,
        fontSize: 40,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "none",
        animation: "fade",
        combineMs: 1500,
        maxWordsPerPage: 10,
      },
      yPct: 0.9,
    },
    transitions: {
      primary: "cut",
      secondary: ["fade"],
      durationFrames: 12,
      frequency: 0.05,
      avoid: ["VFX of any kind", "heavy color grading", "on-screen copy beyond the credit", "transition effects"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "ease-in-out",
      textAnimation: "fade",
      textUnit: "line",
      stagger: 0,
      kenBurns: false,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["end-card", "logo-reveal", "small corner credit 'Shot on iPhone <model>' + creator name"],
    sound: {
      music: "one licensed-feel song or pure natural sound; no voiceover",
      bpm: [80, 120],
      sfx: [],
      sfxPerMin: 0,
      duckDb: 12,
    },
    signature: [
      "Real-world footage is the only hero - no product shots",
      "A tiny 'Shot on iPhone' credit with the creator's name",
      "Zero VFX, near-natural color",
      "Cut to a single song, then a minimal logo end card",
    ],
    avoid: ["motion graphics", "stylized LUTs", "captions or headlines", "voiceover"],
    agentNotes:
      "Use only the user's real footage; never fake it. Pick the 8-15 best shots, cut them to one song (or natural sound) on loose beats, hold hero moments 3-5s. Grade: lift exposure where needed, keep skin natural, protect highlights. The only text: a small white credit ('Shot on iPhone <model> by <name>') lower-left for 2-3s, and a centered end card with a logo-sized mark. No transitions beyond hard cuts and a final fade.",
  },
  {
    id: "linear-launch",
    name: "Linear launch",
    category: "brand",
    archetype: "saas_launch",
    description: "Dark, precise product release: real UI on tilted planes, ease-out-expo snaps, short sentence-case cards, no voiceover.",
    inspiredBy: "Linear release videos",
    tags: ["saas", "launch", "product", "dark ui", "linear", "changelog", "startup"],
    format: {
      aspect: "16:9",
      fps: 60,
      durationSec: { min: 30, typical: 60, max: 90 },
    },
    pacing: {
      aslSec: 2.2,
      cutStyle: "beat",
      beatSync: "loose",
      maxSilenceMs: 0,
      keepFillers: false,
      hook: "The product (or one unmistakable UI artifact) is on screen within 3s; the first card states the single job-to-be-done in <=8 words.",
      ending: "logo_sting",
    },
    grade: {
      exposure: 0,
      contrast: 1.05,
      saturation: 1,
      vibrance: 0,
      temperature: -0.03,
      tint: 0,
      highlights: 0,
      shadows: 0,
      fade: 0,
      vignette: 0.15,
      grain: 0.04,
      glow: 0.2,
      look: "near-black void with a soft indigo glow behind the UI and subtle noise",
    },
    palette: {
      background: "#08090A",
      foreground: "#F7F8F8",
      accents: ["#5E6AD2", "#8A8F98"],
      rule: "monochrome base, a single indigo accent; glows at 15-25% opacity",
    },
    typography: {
      title: {
        fontFamily: "Inter",
        originalFont: "Inter Display",
        fontWeight: 600,
        textTransform: "none",
        letterSpacing: -0.025,
        lineHeight: 1.1,
        color: "#F7F8F8",
        sizePctH: 7.5,
      },
      body: {
        fontFamily: "Inter",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#8A8F98",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Geist Mono",
        originalFont: "keyboard shortcut chips",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: 0,
        color: "#F7F8F8",
        sizePctH: 2.8,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Inter",
        fontWeight: 500,
        fontSize: 44,
        color: "#F7F8F8",
        activeColor: "#F7F8F8",
        textTransform: "none",
        animation: "fade",
        combineMs: 1200,
        maxWordsPerPage: 8,
        letterSpacing: -0.01,
      },
      yPct: 0.86,
    },
    transitions: {
      primary: "cut",
      secondary: ["blur", "push", "zoom-in"],
      durationFrames: 8,
      frequency: 0.3,
      avoid: ["bouncy springs", "flash or glitch transitions", "rainbow gradients", "stock footage", "voiceover"],
    },
    motion: {
      enter: "rise-blur",
      exit: "blur",
      easing: "smooth",
      textAnimation: "mask-up",
      textUnit: "word",
      stagger: 2,
      idleLoop: "drift",
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 0,
    },
    overlays: [
      "browser-window",
      "cursor-click",
      "glow-orbs",
      "grid-background",
      "logo-reveal",
      "keyboard shortcut chips",
      "3D-tilted UI plane",
    ],
    sound: {
      music: "ambient electronic / minimal pulses, no narration",
      bpm: [90, 120],
      sfx: ["click", "tick", "whoosh"],
      sfxPerMin: 12,
      duckDb: 12,
    },
    signature: [
      "Real dark-mode UI as the hero, floating on 3D-tilted planes in a near-black void",
      "Ease-out-expo motion: fast start, long deceleration, zero overshoot",
      "Short sentence-case cards (<=8 words) between UI beats",
      "Keyboard-shortcut chips and a smooth cursor with zoom-to-click",
      "No voiceover - ambient electronic and soft UI ticks only",
    ],
    avoid: ["bouncy UI chrome", "invented UI", "purple-to-blue gradient backgrounds", "dense paragraphs", "busy stock music"],
    agentNotes:
      "Reported: 45-90s per release, one job-to-be-done, dark-mode UI with minimal narration; Linear's transitions use ease-out-expo (front-loaded). Rebuild the real UI as components (never invent it); tilt planes rotateX 10-20deg with perspective ~1600px and push the camera to the element being used; cursor follows smooth bezier paths with a click pulse and 1.4-1.8x zoom-to-click. Staggers ~50ms, durations 300-600ms, no overshoot. One indigo glow behind the hero UI at 15-25% opacity plus 3-5% noise. End on the logo and one line.",
  },
  {
    id: "vercel-launch",
    name: "Vercel launch",
    category: "brand",
    archetype: "saas_launch",
    description:
      "Developer-platform launch: pure black and white, Geist type, 1px grid lines, crisp <=250ms ease-out motion, terminal moments.",
    inspiredBy: "Vercel launch videos and Ship keynotes",
    tags: ["saas", "developer", "launch", "vercel", "geist", "black and white", "terminal"],
    format: {
      aspect: "16:9",
      fps: 60,
      durationSec: { min: 20, typical: 45, max: 90 },
    },
    pacing: {
      aslSec: 2,
      cutStyle: "beat",
      beatSync: "strict",
      maxSilenceMs: 0,
      keepFillers: false,
      hook: "A product artifact in the first 3s: a deploy command typing into a terminal or a URL resolving, plus one 3-5 word headline.",
      ending: "logo_sting",
    },
    grade: {
      exposure: 0,
      contrast: 1.1,
      saturation: 1,
      vibrance: 0,
      temperature: 0,
      tint: 0,
      highlights: 0,
      shadows: -0.05,
      fade: 0,
      vignette: 0,
      grain: 0.03,
      look: "pure black and white, hairline grids, no atmosphere",
    },
    palette: {
      background: "#000000",
      foreground: "#EDEDED",
      accents: ["#FFFFFF", "#0070F3", "#1F1F1F"],
      rule: "black and white only; blue for links/success states; 1px #1F1F1F grid lines",
    },
    typography: {
      title: {
        fontFamily: "Geist",
        fontWeight: 600,
        textTransform: "none",
        letterSpacing: -0.04,
        lineHeight: 1.05,
        color: "#EDEDED",
        sizePctH: 8,
      },
      body: {
        fontFamily: "Geist",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#A1A1A1",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Geist Mono",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: 0,
        color: "#EDEDED",
        sizePctH: 3,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Geist",
        fontWeight: 500,
        fontSize: 44,
        color: "#EDEDED",
        activeColor: "#EDEDED",
        textTransform: "none",
        animation: "fade",
        combineMs: 1200,
        maxWordsPerPage: 8,
        letterSpacing: -0.01,
      },
      yPct: 0.86,
    },
    transitions: {
      primary: "cut",
      secondary: ["fade", "wipe", "push"],
      durationFrames: 6,
      frequency: 0.25,
      avoid: ["color gradients and glows", "bouncy easing", "transitions longer than ~250ms", "stock footage"],
    },
    motion: {
      enter: "rise",
      exit: "fade",
      easing: { type: "bezier", x1: 0, y1: 0, x2: 0.2, y2: 1 },
      textAnimation: "rise",
      textUnit: "word",
      stagger: 2,
      idleLoop: "drift",
      kenBurns: false,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["terminal-window", "browser-window", "grid-background", "cursor-click", "logo-reveal", "stat-grid", "light-sweep"],
    sound: {
      music: "minimal electronic with precise pulses",
      bpm: [100, 128],
      sfx: ["click", "tick", "typewriter", "whoosh"],
      sfxPerMin: 14,
      duckDb: 12,
    },
    signature: [
      "Strict black and white with hairline 1px grid lines",
      "Geist / Geist Mono typography, tightly tracked headlines",
      "Crisp ease-out motion capped around 250ms",
      "Terminal and deploy moments as product proof",
    ],
    avoid: ["glows, gradients and grain-heavy textures", "bouncy springs", "colorful palettes", "long narration"],
    agentNotes:
      "Reported: Vercel caps most transitions near 250ms with a gentle ease-out. Build scenes from black canvas + 1px grid; reveal type word-by-word (2-frame stagger), headlines at -0.04em. Show real product proof: typed CLI commands in Geist Mono, a build log ticking, a URL resolving to the live site in a browser frame, metrics in a stat grid. Cut on the beat; no overshoot; color only for status (blue/green). End on the wordmark with a short line.",
  },
  {
    id: "stripe-launch",
    name: "Stripe launch",
    category: "brand",
    archetype: "saas_launch",
    description:
      "Polished fintech launch: animated gradient mesh, clean light UI cards in isometric 3D, smooth glide easing, confident voiceover.",
    inspiredBy: "Stripe product launch videos",
    tags: ["saas", "fintech", "launch", "gradient mesh", "stripe", "payments", "light ui"],
    format: {
      aspect: "16:9",
      fps: 60,
      durationSec: { min: 30, typical: 75, max: 120 },
    },
    pacing: {
      aslSec: 2.8,
      cutStyle: "continuous",
      beatSync: "loose",
      maxSilenceMs: 250,
      keepFillers: false,
      hook: "A gradient mesh flowing behind the first UI card within 2s and one confident line naming the outcome (not the feature).",
      ending: "logo_sting",
    },
    grade: {
      exposure: 0.05,
      contrast: 1.02,
      saturation: 1.05,
      vibrance: 0.05,
      temperature: 0,
      tint: 0,
      highlights: -0.05,
      shadows: 0.02,
      fade: 0,
      vignette: 0,
      grain: 0.02,
      look: "clean bright product world with a saturated flowing gradient",
    },
    palette: {
      background: "#FFFFFF",
      foreground: "#0A2540",
      accents: ["#635BFF", "#00D4FF", "#FF5996", "#FFB443"],
      rule: "white canvas + navy text; color lives in the gradient mesh and one accent per scene",
    },
    typography: {
      title: {
        fontFamily: "Inter",
        originalFont: "Söhne",
        fontWeight: 600,
        textTransform: "none",
        letterSpacing: -0.03,
        lineHeight: 1.1,
        color: "#0A2540",
        sizePctH: 7.5,
      },
      body: {
        fontFamily: "Inter",
        originalFont: "Söhne",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#425466",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Inter",
        originalFont: "Söhne",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.06,
        color: "#635BFF",
        sizePctH: 2.8,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Inter",
        fontWeight: 500,
        fontSize: 44,
        color: "#0A2540",
        activeColor: "#0A2540",
        textTransform: "none",
        background: { color: "rgba(255,255,255,0.9)", padding: 12, radius: 10 },
        animation: "fade",
        combineMs: 1200,
        maxWordsPerPage: 8,
      },
      yPct: 0.86,
    },
    transitions: {
      primary: "push",
      secondary: ["fade", "zoom-in", "blur"],
      durationFrames: 14,
      frequency: 0.6,
      avoid: ["dark grungy textures", "glitch or flash transitions", "bouncy cartoon motion"],
    },
    motion: {
      enter: "rise",
      exit: "fade",
      easing: "ease",
      textAnimation: "rise",
      textUnit: "word",
      stagger: 2,
      idleLoop: "float",
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 3,
    },
    overlays: [
      "gradient-mesh",
      "browser-window",
      "device-frame",
      "stat-grid",
      "line-chart",
      "cursor-click",
      "logo-reveal",
      "isometric 3D card stack",
    ],
    sound: {
      music: "polished, optimistic upbeat electronic",
      bpm: [100, 124],
      sfx: ["click", "whoosh", "sparkle", "tick"],
      sfxPerMin: 10,
      duckDb: 16,
    },
    signature: [
      "Flowing multi-color gradient mesh behind clean white UI",
      "Light UI cards stacked in isometric 3D space",
      "Smooth glide easing with one continuous camera",
      "Navy-on-white type with a single accent per scene",
    ],
    avoid: ["dark mode by default", "grain and grunge", "harsh contrast", "fake dashboards"],
    agentNotes:
      "Approx Stripe launch grammar: white canvas, navy (#0A2540) type, a slowly flowing gradient mesh (#635BFF, #00D4FF, #FF5996, #FFB443) as the only big color; real UI cards float in isometric 3D (rotateX ~55deg, rotateZ ~-45deg) and assemble with 80-120ms staggers; camera glides continuously instead of cutting. Lead with outcomes and numbers (stat grid, line chart drawing on). Confident VO ~150 wpm with an optimistic electronic bed. End on the wordmark.",
  },
  {
    id: "raycast-launch",
    name: "Raycast launch",
    category: "brand",
    archetype: "saas_launch",
    description:
      "Keyboard-first launch teaser: dark glassy command bar, red glow, emoji tile grids, list actions ticking through on the beat.",
    inspiredBy: "Raycast launch teasers",
    tags: ["saas", "launch", "teaser", "raycast", "command bar", "glass", "keyboard"],
    format: {
      aspect: "16:9",
      fps: 60,
      durationSec: { min: 15, typical: 30, max: 60 },
    },
    pacing: {
      aslSec: 1.6,
      cutStyle: "beat",
      beatSync: "strict",
      maxSilenceMs: 0,
      keepFillers: false,
      hook: "Within the first second: a cropped dark fragment of the glowing command bar typing a query; a result list ticks through on the beat.",
      ending: "logo_sting",
    },
    grade: {
      exposure: -0.05,
      contrast: 1.1,
      saturation: 1.05,
      vibrance: 0.05,
      temperature: 0,
      tint: 0,
      highlights: 0,
      shadows: -0.05,
      fade: 0,
      vignette: 0.25,
      grain: 0.05,
      glow: 0.35,
      look: "dark glass: near-black, red/pink bloom behind translucent panels",
    },
    palette: {
      background: "#0A0A0A",
      foreground: "#FFFFFF",
      accents: ["#FF6363", "#FF8A8A", "#2A2A2A"],
      rule: "near-black + one red glow; glass panels at 60-70% opacity",
    },
    typography: {
      title: {
        fontFamily: "Inter",
        fontWeight: 600,
        textTransform: "none",
        letterSpacing: -0.03,
        color: "#FFFFFF",
        sizePctH: 7,
      },
      body: {
        fontFamily: "Inter",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#9C9C9D",
        sizePctH: 3.2,
      },
      callout: {
        fontFamily: "Inter",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFFFFF",
        sizePctH: 3,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Inter",
        fontWeight: 500,
        fontSize: 44,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "none",
        animation: "fade",
        combineMs: 1000,
        maxWordsPerPage: 8,
      },
      yPct: 0.86,
    },
    transitions: {
      primary: "cut",
      secondary: ["blur", "zoom-in", "flash"],
      durationFrames: 6,
      frequency: 0.3,
      avoid: ["full product walkthroughs", "light backgrounds", "long voiceover"],
    },
    motion: {
      enter: "pop",
      exit: "blur",
      easing: "snappy",
      textAnimation: "rise-blur",
      textUnit: "word",
      stagger: 2,
      idleLoop: "pulse",
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 4,
    },
    overlays: ["glow-orbs", "cursor-click", "logo-reveal", "glassy command bar", "emoji tile grid", "keyboard shortcut chips"],
    sound: {
      music: "punchy minimal electronic with a tight kick on the cuts",
      bpm: [110, 128],
      sfx: ["click", "tick", "pop", "whoosh"],
      sfxPerMin: 20,
      duckDb: 12,
    },
    signature: [
      "Cropped dark fragments of a glowing glass command bar",
      "A grid of emoji tiles with one highlighted",
      "Result lists ticking through on the beat",
      "Red/pink bloom behind translucent panels",
    ],
    avoid: ["bright white UI", "slow tutorial pacing", "multiple accent colors"],
    agentNotes:
      "Reported teaser grammar: cropped, dark fragments; a glowing search bar; a grid of emoji tiles with one highlighted; a list of AI actions ticking through - a teaser, not a walkthrough. Keep every shot under ~2s, cut strictly on the beat, keyboard clicks as SFX. Glass panels: 60-70% opacity, 24-40px backdrop blur, 1px light border; one red/pink glow behind (approx #FF6363). Snappy springs with <=4% overshoot. End on the logo.",
  },
  {
    id: "nike-ad",
    name: "Nike ad",
    category: "brand",
    archetype: "brand_film",
    description:
      "Athletic manifesto spot: gritty high-contrast montage cut to an anthem, sweat-and-breath close-ups, ultra-bold condensed caps.",
    inspiredBy: "Nike advertising",
    tags: ["sports", "ad", "commercial", "manifesto", "athletes", "motivation", "nike"],
    format: {
      aspect: "16:9",
      fps: 24,
      durationSec: { min: 15, typical: 60, max: 120 },
    },
    pacing: {
      aslSec: 1.2,
      cutStyle: "beat",
      beatSync: "strict",
      maxSilenceMs: 0,
      keepFillers: false,
      hook: "0-3s: an extreme close-up of an athlete (breath, sweat, eyes) and one bold manifesto line in voiceover or type, with the anthem entering underneath.",
      ending: "logo_sting",
    },
    grade: {
      exposure: -0.05,
      contrast: 1.3,
      saturation: 0.85,
      vibrance: -0.05,
      temperature: 0,
      tint: 0,
      highlights: -0.1,
      shadows: -0.22,
      fade: 0,
      lut: "bleach-bypass",
      vignette: 0.2,
      grain: 0.15,
      look: "gritty high contrast: crushed blacks, muted color or full B&W passages, film grain",
    },
    palette: {
      background: "#000000",
      foreground: "#FFFFFF",
      accents: ["#FA5400", "#CEFF00"],
      rule: "black/white type; color comes from the footage (orange/volt accents approx)",
    },
    typography: {
      title: {
        fontFamily: "Anton",
        originalFont: "Futura Condensed ExtraBold (Nike Futura ND)",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: -0.005,
        lineHeight: 0.92,
        color: "#FFFFFF",
        sizePctH: 16,
      },
      body: {
        fontFamily: "Inter",
        originalFont: "Helvetica Neue",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFFFFF",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Bebas Neue",
        originalFont: "Futura Condensed ExtraBold",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.01,
        color: "#FFFFFF",
        sizePctH: 12,
      },
    },
    captions: {
      mode: "callout_only",
      style: {
        fontFamily: "Anton",
        fontWeight: 400,
        fontSize: 120,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "uppercase",
        animation: "none",
        combineMs: 300,
        maxWordsPerPage: 2,
        letterSpacing: 0,
        lineHeight: 0.92,
      },
      yPct: 0.5,
    },
    transitions: {
      primary: "cut",
      secondary: ["dip-to-black", "flash"],
      durationFrames: 2,
      frequency: 0.05,
      avoid: ["soft dissolves", "pastel or bright commercial grades", "small polite type", "product-feature talk"],
    },
    motion: {
      enter: "zoom",
      exit: "fade",
      easing: "snappy",
      textAnimation: "slam",
      textUnit: "word",
      stagger: 4,
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 0,
    },
    overlays: ["kinetic-title", "logo-reveal", "end-card"],
    sound: {
      music: "anthemic hip-hop / orchestral build to a drop; hard cut to silence before the final line",
      bpm: [85, 140],
      sfx: ["impact", "bass-hit", "whoosh", "riser"],
      sfxPerMin: 12,
      duckDb: 10,
    },
    signature: [
      "Ultra-bold condensed Futura-style caps filling the frame",
      "Sweat, breath and eyes in extreme close-up; slow-motion hero moments",
      "A rhythmic athletic montage cut tightly to an anthem",
      "Silence, then the logo and a three-word manifesto line",
    ],
    avoid: ["feature lists", "soft transitions", "bright cheerful grades", "busy graphics"],
    agentNotes:
      "Structure: tension (quiet, close, breath) -> build (montage tightening from ~3s to ~0.5s shots on the beat) -> drop (hero slow-mo, 120-240fps feel) -> hard cut to silence -> one manifesto line -> logo end card. Type: Futura Condensed ExtraBold-style caps (Anton fallback) stacked left-flush or centered at 10-20% of frame height, slammed on the beat. Sound design carries realism: breath, footsteps, ball impacts, crowd swell. Grade gritty: crush blacks, mute color or go B&W for flashbacks.",
  },
];
