import type { StyleDNA } from "../schema";

/**
 * Genre and look presets (not tied to a single creator). The last three
 * (motion showreel, data story, article highlight) are the most requested
 * AI motion-video formats in the research notes.
 */
export const GENRE_STYLES: StyleDNA[] = [
  {
    id: "a24-trailer",
    name: "A24 trailer",
    category: "genre",
    archetype: "trailer",
    description:
      "Arthouse/horror trailer: cryptic imagery, drones and a repeated unsettling sound, sparse cards on black, accelerating montage to a smash cut.",
    inspiredBy: "A24 film trailers",
    tags: ["trailer", "horror", "arthouse", "indie film", "cinematic", "title cards", "a24"],
    format: {
      aspect: "16:9",
      fps: 24,
      durationSec: { min: 45, typical: 120, max: 150 },
      letterbox: 2.39,
    },
    pacing: {
      aslSec: 3,
      cutStyle: "mixed",
      beatSync: "loose",
      maxSilenceMs: 0,
      keepFillers: true,
      hook: "Open mid-movement on a cryptic image and one unsettling line of dialogue - no context, no exposition.",
      ending: "outro_card",
    },
    grade: {
      exposure: -0.05,
      contrast: 1.05,
      saturation: 0.75,
      vibrance: -0.1,
      temperature: 0,
      tint: 0.02,
      highlights: -0.2,
      shadows: 0.02,
      fade: 0.06,
      lut: "film-print",
      vignette: 0.15,
      grain: 0.3,
      look: "muted print film: low saturation, softly lifted blacks, heavy grain",
    },
    palette: {
      background: "#000000",
      foreground: "#F2EFEA",
      accents: ["#B23A2E", "#C9B37E"],
      rule: "black cards, off-white type; color comes only from the film",
    },
    typography: {
      title: {
        fontFamily: "EB Garamond",
        originalFont: "film-specific custom title",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.22,
        color: "#F2EFEA",
        sizePctH: 4.5,
      },
      body: {
        fontFamily: "Inter",
        fontWeight: 500,
        textTransform: "uppercase",
        letterSpacing: 0.25,
        color: "#F2EFEA",
        sizePctH: 2.8,
      },
      callout: {
        fontFamily: "Cormorant Garamond",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: 0.02,
        color: "#F2EFEA",
        italic: true,
        sizePctH: 4,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Inter",
        fontWeight: 500,
        fontSize: 40,
        color: "#F2EFEA",
        activeColor: "#F2EFEA",
        textTransform: "none",
        animation: "fade",
        combineMs: 1500,
        maxWordsPerPage: 10,
      },
      yPct: 0.86,
    },
    transitions: {
      primary: "cut",
      secondary: ["dip-to-black", "flash"],
      durationFrames: 6,
      frequency: 0.3,
      avoid: ["whips, zooms or spins", "bright saturated color", "explaining the plot", "upbeat music"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "ease-in-out",
      textAnimation: "fade",
      textUnit: "line",
      stagger: 6,
      idleLoop: "drift",
      kenBurns: true,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["letterbox", "quote-card", "end-card", "festival laurels"],
    sound: {
      music: "drones under dialogue, a repeated unsettling motif, rhythmic pulses; a re-contextualized needle drop",
      bpm: [60, 100],
      sfx: ["braam", "impact", "riser", "sub-drop", "bass-hit"],
      sfxPerMin: 8,
      duckDb: 10,
    },
    signature: [
      "Cryptic imagery and unsettling repetition instead of exposition",
      "Drones under quiet dialogue, a repeated sound motif, hits on title cards",
      "Sparse, wide-tracked cards on black (critic quotes, laurels, title)",
      "Act 3 strobe montage accelerating to 0.3-1s shots, then silence and a smash cut",
    ],
    avoid: ["plot summaries", "bright commercial grading", "jump-scare stingers every few seconds", "busy motion graphics"],
    agentNotes:
      "Three acts: (1) 4-8s slow drifting shots under a drone, one unsettling line; (2) pulses build, shots 2-3s, title/critic cards land on hits; (3) accelerating montage to 0.3-1s shots, a sudden silence, smash cut to black, title card, a short stinger scene, date card. Repeat one sound (a voice line, a click, a breath) as a motif. Cards: small centered off-white serif or wide-tracked sans caps on black, ~2-3s each. Grade muted print film with heavy grain; letterbox 2.39.",
  },
  {
    id: "wes-anderson",
    name: "Wes Anderson",
    category: "genre",
    archetype: "auteur_look",
    description:
      "Symmetrical pastel storybook: dead-center compositions, Futura chapter cards, 90-degree whip pans, overhead inserts, deadpan holds.",
    inspiredBy: "Wes Anderson's films",
    tags: ["wes anderson", "symmetry", "pastel", "storybook", "film look", "tiktok trend", "chapters"],
    format: {
      aspect: "16:9",
      fps: 24,
      durationSec: { min: 15, typical: 60, max: 180 },
      letterbox: 1.85,
    },
    pacing: {
      aslSec: 4.5,
      cutStyle: "hard",
      beatSync: "loose",
      maxSilenceMs: 0,
      keepFillers: true,
      hook: "A perfectly centered establishing tableau plus a Futura chapter card ('Chapter One: The Arrival'), narrated deadpan.",
      ending: "outro_card",
    },
    grade: {
      exposure: 0.05,
      contrast: 0.9,
      saturation: 0.95,
      vibrance: -0.05,
      temperature: 0.1,
      tint: 0.04,
      highlights: -0.1,
      shadows: 0.08,
      fade: 0.06,
      lut: "pastel-dream",
      vignette: 0,
      grain: 0.15,
      look: "flattened pastel storybook: warm, low contrast, 3-5 color palette, 35mm grain",
    },
    palette: {
      background: "#F4C7C3",
      foreground: "#2B2A33",
      accents: ["#F2D06B", "#9DC3C2", "#C1554D", "#7E5A9B"],
      rule: "3-5 pastels per piece, blocked symmetrically",
    },
    typography: {
      title: {
        fontFamily: "Jost",
        originalFont: "Futura Bold",
        fontWeight: 700,
        textTransform: "uppercase",
        letterSpacing: 0.08,
        color: "#F7E7B4",
        sizePctH: 6,
      },
      body: {
        fontFamily: "Jost",
        originalFont: "Futura",
        fontWeight: 500,
        textTransform: "uppercase",
        letterSpacing: 0.06,
        color: "#2B2A33",
        sizePctH: 3.2,
      },
      callout: {
        fontFamily: "Courier Prime",
        originalFont: "typewriter",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: 0,
        color: "#2B2A33",
        sizePctH: 3.2,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Jost",
        fontWeight: 500,
        fontSize: 44,
        color: "#F7E7B4",
        activeColor: "#F7E7B4",
        textTransform: "uppercase",
        animation: "typewriter",
        combineMs: 1500,
        maxWordsPerPage: 8,
        letterSpacing: 0.06,
      },
      yPct: 0.88,
    },
    transitions: {
      primary: "cut",
      secondary: ["whip"],
      durationFrames: 8,
      frequency: 0.12,
      avoid: ["handheld shake", "dutch angles", "off-center framing", "dissolves", "teal-orange grading"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "ease-in-out",
      textAnimation: "typewriter",
      textUnit: "char",
      stagger: 1,
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 0,
    },
    overlays: ["chapter-card", "letterbox", "kinetic-title", "overhead insert of hands/objects", "illustrated map"],
    sound: {
      music: "Desplat-like harpsichord, pizzicato strings, mandolin/balalaika, cimbalom; 60s folk needle drops",
      bpm: [90, 130],
      sfx: ["whoosh", "typewriter", "ding"],
      sfxPerMin: 4,
      duckDb: 12,
    },
    signature: [
      "Dead-center symmetry with a planimetric (perpendicular) camera",
      "Pastel 3-5 color palette, flattened warm contrast",
      "Centered Futura caps chapter cards, typed on",
      "Lateral whip pans in 90-degree increments",
      "Top-down inserts of hands and objects; deadpan holds",
    ],
    avoid: ["rule-of-thirds framing", "handheld or shaky camera", "saturated neon color", "fast montage cutting"],
    agentNotes:
      "Frame every shot dead center with the camera perpendicular to the set; stage people across the frame like garments on a line. Hold compositions 3-8s and cut on action with symmetrical shot-reverse-shot. Move with lateral constant-velocity dollies and 90-degree whip pans (6-10 frames, motion blur). Chapter cards: Futura-style caps centered on a solid pastel or black, typewriter reveal. Grade warm pastel, low contrast, 35mm grain. Music: plucked strings/harpsichord. Use 1.37 pillarbox for flashback sections.",
  },
  {
    id: "cinematic-travel",
    name: "Cinematic travel film",
    category: "genre",
    archetype: "music_montage",
    description:
      "Seamless travel montage: in-motion whip/spin/zoom transitions, aggressive speed ramps, hyper-real teal-orange grade, whoosh on every move.",
    inspiredBy: "Sam Kolder-style travel films",
    tags: ["travel", "cinematic", "drone", "speed ramp", "transitions", "teal orange", "montage"],
    format: {
      aspect: "16:9",
      fps: 24,
      durationSec: { min: 45, typical: 120, max: 240 },
      letterbox: 2.39,
    },
    pacing: {
      aslSec: 1.4,
      cutStyle: "beat",
      beatSync: "strict",
      maxSilenceMs: 0,
      keepFillers: false,
      hook: "A drone/FPV reveal or a chain of seamless in-motion transitions landing on the first drop within 5s.",
      ending: "fade",
    },
    grade: {
      exposure: 0.05,
      contrast: 1.15,
      saturation: 1.2,
      vibrance: 0.15,
      temperature: 0.05,
      tint: 0,
      highlights: -0.2,
      shadows: -0.05,
      fade: 0,
      lut: "teal-orange",
      vignette: 0.15,
      grain: 0.05,
      glow: 0.1,
      look: "hyper-real teal-orange: saturated, warm skin and highlights, teal shadows, light halation",
    },
    palette: {
      background: "#0B1A20",
      foreground: "#FFFFFF",
      accents: ["#FF9E57", "#0E4A5C"],
      rule: "complementary teal/orange split",
    },
    typography: {
      title: {
        fontFamily: "Montserrat",
        fontWeight: 300,
        textTransform: "uppercase",
        letterSpacing: 0.3,
        color: "#FFFFFF",
        sizePctH: 5,
      },
      body: {
        fontFamily: "Montserrat",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.2,
        color: "#FFFFFF",
        sizePctH: 2.8,
      },
      callout: {
        fontFamily: "Playfair Display",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: 0.02,
        color: "#FFFFFF",
        italic: true,
        sizePctH: 6,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Montserrat",
        fontWeight: 400,
        fontSize: 40,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "uppercase",
        animation: "fade",
        combineMs: 1200,
        maxWordsPerPage: 6,
        letterSpacing: 0.2,
      },
      yPct: 0.86,
    },
    transitions: {
      primary: "whip",
      secondary: ["spin", "zoom-in", "zoom-out", "slide", "light-leak"],
      durationFrames: 12,
      frequency: 0.55,
      avoid: ["cross dissolves", "static locked-off shots", "flat ungraded log footage", "the same transition twice in a row"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "ease-in-out",
      textAnimation: "rise-blur",
      textUnit: "char",
      stagger: 1,
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 0,
    },
    overlays: ["letterbox", "kinetic-title", "map-route"],
    sound: {
      music: "epic electronic / indie / cinematic with a clear drop",
      bpm: [100, 130],
      sfx: ["whoosh", "swoosh", "riser", "impact"],
      sfxPerMin: 25,
      duckDb: 8,
    },
    signature: [
      "Seamless transitions that continue one camera motion across locations",
      "Speed ramps (100% -> 800% -> 100%) through every transition",
      "Hyper-real saturated or teal-orange grade, 2.39 letterbox",
      "A whoosh on every transition, risers into the drop",
    ],
    avoid: ["dissolves", "static shots longer than 3s", "talking-head segments", "unstabilized footage"],
    agentNotes:
      "Reported technique: match one camera motion across locations (end clip A mid-whip/spin/push, start clip B continuing the same direction) and hide the cut in the motion blur; masking/object wipes for variety; ~20-frame transition windows (10 each side). Interpret 60/120fps footage at 23.976 so everything plays slightly slow, then ramp 100%->800%->100% around cuts. Cut strictly to the music, save the best FPV/drone reveal for the drop. Location titles: wide-tracked thin caps, centered, fading in by letter.",
  },
  {
    id: "vhs-90s",
    name: "90s VHS",
    category: "genre",
    archetype: "retro_texture",
    description:
      "Home-video camcorder look: 4:3 pillarbox, chroma bleed, scanlines, rolling tracking bands, VCR on-screen text and a date stamp.",
    inspiredBy: "1990s VHS camcorders and VCR playback",
    tags: ["vhs", "retro", "90s", "camcorder", "glitch", "nostalgia", "analog"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 10, typical: 45, max: 300 },
      letterbox: 1.33,
    },
    pacing: {
      aslSec: 4,
      cutStyle: "hard",
      beatSync: "none",
      maxSilenceMs: 0,
      keepFillers: true,
      hook: "A blue 'PLAY >' screen or a tracking-glitch burst straight into the first shot, timestamp already ticking.",
      ending: "abrupt",
    },
    grade: {
      exposure: 0.05,
      contrast: 0.9,
      saturation: 1.15,
      vibrance: 0.1,
      temperature: 0.03,
      tint: 0.06,
      highlights: 0.1,
      shadows: 0.05,
      fade: 0.14,
      lut: "vhs",
      vignette: 0.25,
      grain: 0.35,
      chromaticAberration: 3,
      glow: 0.2,
      look: "worn VHS: soft image, lifted blacks, bloomed highlights, color bleed, magenta/green drift",
    },
    palette: {
      background: "#0022CC",
      foreground: "#FFFFFF",
      accents: ["#FFB000", "#3BFF4A", "#FF2A2A"],
      rule: "OSD text white/green, camcorder date orange-yellow, REC dot red, blue screen between tapes",
    },
    typography: {
      title: {
        fontFamily: "VT323",
        originalFont: "VCR OSD Mono",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.04,
        color: "#FFFFFF",
        shadow: { color: "rgba(255,255,255,0.5)", blur: 6, x: 0, y: 0 },
        sizePctH: 7,
      },
      body: {
        fontFamily: "VT323",
        originalFont: "VCR OSD Mono",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.04,
        color: "#FFFFFF",
        shadow: { color: "rgba(255,255,255,0.4)", blur: 4, x: 0, y: 0 },
        sizePctH: 4.5,
      },
      callout: {
        fontFamily: "VT323",
        originalFont: "camcorder date stamp",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.04,
        color: "#FFB000",
        sizePctH: 4.5,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "VT323",
        fontWeight: 400,
        fontSize: 56,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "uppercase",
        shadow: { color: "rgba(255,255,255,0.4)", blur: 4, x: 0, y: 0 },
        animation: "typewriter",
        combineMs: 1000,
        maxWordsPerPage: 6,
      },
      yPct: 0.85,
    },
    transitions: {
      primary: "glitch",
      secondary: ["flash", "dip-to-black"],
      durationFrames: 5,
      frequency: 0.35,
      avoid: ["crisp 4K sharpness", "smooth modern motion graphics", "clean digital blacks", "widescreen framing"],
    },
    motion: {
      enter: "glitch",
      exit: "glitch",
      easing: "linear",
      textAnimation: "typewriter",
      textUnit: "char",
      stagger: 1,
      idleLoop: "wiggle",
      kenBurns: false,
      shake: true,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["vhs-overlay", "letterbox", "OSD text 'PLAY >' / 'REC' / 'SP'", "camcorder date stamp", "rolling tracking band"],
    sound: {
      music: "lo-fi synth or tape-saturated library music",
      bpm: [80, 110],
      sfx: ["glitch", "click", "tick"],
      sfxPerMin: 4,
      duckDb: 10,
    },
    signature: [
      "4:3 pillarbox with VCR on-screen text (PLAY, REC, SP)",
      "Chroma bleed + RGB offset + scanlines",
      "Rolling tracking bands and static bursts between clips",
      "Camcorder date stamp in orange-yellow, bottom right",
    ],
    avoid: ["clean digital sharpness", "modern sans-serif titles", "smooth gimbal moves", "16:9 full-bleed frames"],
    agentNotes:
      "Pillarbox to 4:3 (letterbox 1.33). Degrade: soften ~1-1.5px, chroma offset red +2px / blue -2px, horizontal chroma blur, scanlines (2px period at 10-20%), noise ~40-45 on Premiere's scale, a 5-15%-high tracking band rolling every 3-8s with 5-20px horizontal displacement, wave warp (square, width 600, speed 0.1). OSD in VCR OSD Mono (VT323 fallback): 'PLAY >' top-left, 'SP' / timecode, camcorder date 'JAN. 12 1996' bottom-right in orange-yellow. Audio: tape hiss, low-pass ~8-10kHz, slight wow/flutter, mono.",
  },
  {
    id: "corporate-explainer",
    name: "Corporate explainer",
    category: "genre",
    archetype: "edu_animation",
    description:
      "Friendly flat 2D explainer: problem -> solution -> 3 steps -> CTA, brand-colored keywords, icons popping in with overshoot.",
    inspiredBy: "Animated SaaS and corporate explainer videos",
    tags: ["explainer", "corporate", "saas", "flat animation", "b2b", "onboarding", "2d"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 45, typical: 75, max: 120 },
    },
    pacing: {
      aslSec: 4,
      cutStyle: "continuous",
      beatSync: "loose",
      maxSilenceMs: 300,
      keepFillers: false,
      hook: "Name the viewer's problem in the first sentence with a relatable character in a frustrating moment (0-8s).",
      ending: "cta",
    },
    grade: {
      exposure: 0,
      contrast: 1,
      saturation: 1,
      vibrance: 0,
      temperature: 0,
      tint: 0,
      highlights: 0,
      shadows: 0,
      fade: 0,
      vignette: 0,
      grain: 0,
      look: "clean flat vector, brand colors on an off-white canvas",
    },
    palette: {
      background: "#F7F7FB",
      foreground: "#1B1B3A",
      accents: ["#4F46E5", "#22C55E", "#F59E0B"],
      rule: "brand primary + 2 secondaries on off-white; one keyword per line in the primary",
    },
    typography: {
      title: {
        fontFamily: "Poppins",
        fontWeight: 700,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#1B1B3A",
        sizePctH: 7,
      },
      body: {
        fontFamily: "Inter",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#3F3F5A",
        sizePctH: 3.6,
      },
      callout: {
        fontFamily: "Poppins",
        fontWeight: 700,
        textTransform: "none",
        letterSpacing: 0,
        color: "#4F46E5",
        sizePctH: 4.5,
      },
    },
    captions: {
      mode: "phrase",
      style: {
        fontFamily: "Inter",
        fontWeight: 600,
        fontSize: 46,
        color: "#1B1B3A",
        activeColor: "#1B1B3A",
        emphasisColor: "#4F46E5",
        textTransform: "none",
        background: {
          color: "rgba(255,255,255,0.92)",
          padding: 14,
          radius: 12,
        },
        animation: "fade",
        combineMs: 1200,
        maxWordsPerPage: 8,
      },
      yPct: 0.88,
    },
    transitions: {
      primary: "wipe",
      secondary: ["iris", "push", "slide"],
      durationFrames: 12,
      frequency: 0.7,
      avoid: ["live-action stock footage", "dark moody grades", "dense on-screen paragraphs", "purple-to-blue gradient backgrounds"],
    },
    motion: {
      enter: "pop",
      exit: "fade",
      easing: "playful",
      textAnimation: "rise",
      textUnit: "word",
      stagger: 3,
      idleLoop: "float",
      kenBurns: false,
      shake: false,
      motionBlur: false,
      overshootPct: 12,
    },
    overlays: [
      "kinetic-title",
      "stat-grid",
      "browser-window",
      "device-frame",
      "bar-chart",
      "arrow-callout",
      "end-card",
      "flat character scene",
    ],
    sound: {
      music: "upbeat corporate pop: ukulele, claps, light synth",
      bpm: [100, 120],
      sfx: ["pop", "swoosh", "click", "ding"],
      sfxPerMin: 18,
      duckDb: 14,
    },
    signature: [
      "Problem -> solution -> how it works (3 steps) -> proof -> CTA",
      "Friendly flat characters and icons popping in with ~10% overshoot",
      "Brand-colored keyword in every title line",
      "Shape wipes and iris transitions between scenes",
    ],
    avoid: ["more than one message per scene", "jargon-heavy narration", "slow pacing past 2 minutes"],
    agentNotes:
      "Reported best practice: 60-90s, one clear message, VO at 130-160 wpm (aim ~145). Script beats: problem (8-12s) -> solution reveal (8s) -> 3 how-it-works steps (~12s each, icon + 3-6 word title + UI snippet) -> proof (stat grid or logo row) -> CTA card (5s). Icons pop with ~10% overshoot and 80-120ms staggers; characters idle-bob; line-art draws on. Use the user's real UI in device frames. Captions on for social cuts.",
  },
  {
    id: "velocity-edit",
    name: "TikTok velocity edit",
    category: "genre",
    archetype: "music_montage",
    description:
      "Beat-synced velocity edit: speed ramps that hit slow motion exactly on the drop, flash + shake on beats, everything cut to the track.",
    inspiredBy: "TikTok / CapCut velocity and beat-sync edits",
    tags: ["tiktok", "velocity", "beat sync", "capcut", "speed ramp", "edit", "reels"],
    format: {
      aspect: "9:16",
      fps: 30,
      durationSec: { min: 7, typical: 15, max: 30 },
    },
    pacing: {
      aslSec: 0.8,
      cutStyle: "beat",
      beatSync: "strict",
      maxSilenceMs: 0,
      keepFillers: false,
      hook: "The first cut lands on the first beat (within 0.5s); the most striking shot sits exactly on the first drop.",
      ending: "loop",
      punchIn: { scale: 1.2, perMin: 40, durFrames: 3 },
    },
    grade: {
      exposure: 0,
      contrast: 1.25,
      saturation: 1.2,
      vibrance: 0.1,
      temperature: 0,
      tint: 0,
      highlights: -0.05,
      shadows: -0.18,
      fade: 0,
      lut: "vivid-pop",
      vignette: 0.25,
      grain: 0.05,
      chromaticAberration: 4,
      look: "contrasty and saturated (or full B&W), RGB split on drops",
    },
    palette: {
      background: "#000000",
      foreground: "#FFFFFF",
      accents: ["#FFFFFF"],
      rule: "the footage carries color; toggle B&W <-> color on drops",
    },
    typography: {
      title: {
        fontFamily: "Playfair Display",
        fontWeight: 600,
        textTransform: "lowercase",
        letterSpacing: 0,
        color: "#FFFFFF",
        italic: true,
        sizePctH: 3.2,
      },
      body: {
        fontFamily: "Montserrat",
        fontWeight: 800,
        textTransform: "uppercase",
        letterSpacing: 0.04,
        color: "#FFFFFF",
        sizePctH: 2.6,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Montserrat",
        fontWeight: 800,
        fontSize: 56,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "uppercase",
        animation: "pop",
        combineMs: 400,
        maxWordsPerPage: 3,
      },
      yPct: 0.5,
    },
    transitions: {
      primary: "cut",
      secondary: ["flash", "zoom-in", "zoom-out", "spin", "glitch", "whip"],
      durationFrames: 3,
      frequency: 0.35,
      avoid: ["cuts off the beat", "long holds", "voiceover", "slow dissolves"],
    },
    motion: {
      enter: "zoom",
      exit: "zoom",
      easing: "snappy",
      textAnimation: "fade",
      textUnit: "word",
      stagger: 2,
      kenBurns: false,
      shake: true,
      motionBlur: true,
      overshootPct: 0,
    },
    overlays: ["small centered lyric / quote text"],
    sound: {
      music: "trending edit audio (phonk, funk, sped-up remixes); no voiceover",
      bpm: [120, 160],
      sfx: ["whoosh", "impact", "bass-hit", "glitch"],
      sfxPerMin: 30,
      duckDb: 0,
    },
    signature: [
      "Speed ramps: fast between beats, 0.2-0.3x slow motion exactly on the beat/drop",
      "White flash (1-2 frames) and 2-3 frame shake on hits",
      "Zoom punches and RGB split on drops",
      "Every cut on a beat, loopable ending",
    ],
    avoid: ["cuts between beats", "talking", "subtitles", "holds longer than ~1.5s"],
    agentNotes:
      "Beat-map the track first. Speed curve per clip (CapCut range 0.1-10x): approach at 1x, ramp to 3-5x between beats, dip to 0.2-0.3x for 4-8 frames ON the beat, ramp back up; use 4-5 control points with smooth speed + motion blur. On strong beats: cut + 1-2 frame white flash + 2-3 frame shake (10-30px) + 1.15-1.3x zoom punch; on drops add 4-8px RGB split or a B&W<->color toggle. Clips 0.4-1.5s (cut every 1-2 beats at 120-160 BPM). Make the last frame loop into the first.",
  },
  {
    id: "news-documentary",
    name: "News documentary",
    category: "genre",
    archetype: "doc_essay",
    description:
      "Broadcast documentary package: interview bites covered by b-roll, two-line lower thirds, Ken Burns on archival, restrained music.",
    inspiredBy: "Broadcast news packages and documentary films",
    tags: ["news", "documentary", "interview", "broadcast", "lower thirds", "journalism", "archival"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 90, typical: 300, max: 3600 },
    },
    pacing: {
      aslSec: 5.5,
      cutStyle: "mixed",
      beatSync: "none",
      maxSilenceMs: 400,
      keepFillers: false,
      hook: "Cold open on the strongest natural-sound moment or soundbite (5-15s), then the narrator frames the central question.",
      ending: "fade",
    },
    grade: {
      exposure: 0,
      contrast: 1.05,
      saturation: 1,
      vibrance: 0,
      temperature: 0,
      tint: 0,
      highlights: -0.1,
      shadows: 0.02,
      fade: 0,
      vignette: 0.05,
      grain: 0,
      look: "neutral broadcast: accurate skin, soft-key interviews against darker backgrounds",
    },
    palette: {
      background: "#0F1A2A",
      foreground: "#FFFFFF",
      accents: ["#C8102E", "#F2F2F2"],
      rule: "one brand bar color for lower thirds and supers only",
    },
    typography: {
      title: {
        fontFamily: "Roboto Condensed",
        fontWeight: 700,
        textTransform: "uppercase",
        letterSpacing: 0.02,
        color: "#FFFFFF",
        sizePctH: 6,
      },
      body: {
        fontFamily: "Roboto",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFFFFF",
        sizePctH: 3,
      },
      callout: {
        fontFamily: "Roboto",
        fontWeight: 700,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFFFFF",
        sizePctH: 4.2,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Roboto",
        fontWeight: 500,
        fontSize: 44,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "none",
        background: { color: "rgba(0,0,0,0.7)", padding: 10, radius: 2 },
        animation: "fade",
        combineMs: 1500,
        maxWordsPerPage: 10,
      },
      yPct: 0.88,
    },
    transitions: {
      primary: "cut",
      secondary: ["fade", "dip-to-black"],
      durationFrames: 15,
      frequency: 0.06,
      avoid: ["flashy transitions", "music over soundbites", "unsourced claims on screen", "meme inserts"],
    },
    motion: {
      enter: "wipe",
      exit: "wipe",
      easing: "ease-in-out",
      textAnimation: "fade",
      textUnit: "line",
      stagger: 3,
      idleLoop: "ken-burns",
      kenBurns: true,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: [
      "lower-third",
      "map-route",
      "bar-chart",
      "line-chart",
      "quote-card",
      "location / date super",
      "archival photo with Ken Burns",
    ],
    sound: {
      music: "understated strings / ambient beds; natural sound up full between soundbites",
      bpm: [60, 90],
      sfx: ["whoosh"],
      sfxPerMin: 1,
      duckDb: 18,
    },
    signature: [
      "Two-line lower thirds: bold name over regular title",
      "Interview soundbites covered by relevant b-roll, heavy J/L cuts",
      "Ken Burns pushes on archival photos and documents",
      "Restrained music; natural sound carries the scenes",
    ],
    avoid: ["stylized grades", "bouncy animation", "sound effects", "editorializing on-screen text"],
    agentNotes:
      "Lower thirds: name 600-700 weight (~4-4.5% of height) over title 400 (~3%), x 6-10%, y 78-85% inside title-safe, on screen 4-6s, wipe/slide in and out over 300-500ms; discreet in docs, full-width bar in news. Interview bites 8-20s, covered by b-roll on the second half; J/L cuts between scenes. Archival: Ken Burns 1.0->1.08 over 6-8s. Package 1:30-2:30; documentaries in acts separated by dips to black.",
  },
  {
    id: "faceless-documentary",
    name: "Faceless documentary",
    category: "genre",
    archetype: "doc_essay",
    description:
      "Voiceover-only YouTube documentary: constant Ken Burns on stills and archival, dark ambient score, chapter cards, cool desaturated grade.",
    inspiredBy: "Faceless YouTube documentary channels",
    tags: ["faceless", "documentary", "voiceover", "history", "mystery", "true crime", "youtube automation"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 480, typical: 900, max: 1800 },
    },
    pacing: {
      aslSec: 4, // reported: visual change every 3-5s
      cutStyle: "hard",
      beatSync: "none",
      maxSilenceMs: 300,
      keepFillers: false,
      hook: "A mystery question + 'this is the story of...' within 15s over the most dramatic still; tease the ending.",
      ending: "fade",
    },
    grade: {
      exposure: -0.05,
      contrast: 1.15,
      saturation: 0.8,
      vibrance: -0.05,
      temperature: -0.08,
      tint: 0,
      highlights: -0.15,
      shadows: -0.15,
      fade: 0,
      lut: "cool-doc",
      vignette: 0.35,
      grain: 0.15,
      look: "dark cinematic teal: desaturated, cool, heavy vignette",
    },
    palette: {
      background: "#0B0F14",
      foreground: "#E8E8E8",
      accents: ["#C1121F", "#D4A373"],
      rule: "dark cool base; red only for circles/arrows on evidence",
    },
    typography: {
      title: {
        fontFamily: "Cinzel",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.12,
        color: "#E8E8E8",
        sizePctH: 7,
      },
      body: {
        fontFamily: "Oswald",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.06,
        color: "#E8E8E8",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Oswald",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.04,
        color: "#C1121F",
        sizePctH: 4,
      },
    },
    captions: {
      mode: "phrase",
      style: {
        fontFamily: "Inter",
        fontWeight: 600,
        fontSize: 46,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        emphasisColor: "#F2C14E",
        textTransform: "none",
        shadow: { color: "rgba(0,0,0,0.8)", blur: 8, x: 0, y: 2 },
        animation: "fade",
        combineMs: 1400,
        maxWordsPerPage: 9,
      },
      yPct: 0.86,
    },
    transitions: {
      primary: "cut",
      secondary: ["fade", "dip-to-black", "light-leak"],
      durationFrames: 12,
      frequency: 0.15,
      avoid: ["a static image held over 5s", "upbeat music", "bright saturated grades", "an on-camera host"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "ease-in-out",
      textAnimation: "fade",
      textUnit: "word",
      stagger: 3,
      idleLoop: "ken-burns",
      kenBurns: true,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: [
      "chapter-card",
      "map-route",
      "circle-highlight",
      "arrow-callout",
      "quote-card",
      "paper-texture",
      "timeline",
      "newspaper clipping",
    ],
    sound: {
      music: "dark ambient drones + tension pulses",
      bpm: [60, 90],
      sfx: ["whoosh", "sub-drop", "riser", "impact"],
      sfxPerMin: 6,
      duckDb: 16,
    },
    signature: [
      "Voiceover only: every sentence has a matching visual",
      "Constant Ken Burns on stills (1.00 -> 1.10 over ~5s, alternating direction)",
      "Dark ambient score with tension pulses",
      "Chapter title cards splitting a rise-and-fall story",
    ],
    avoid: ["static slideshows", "mismatched stock visuals", "cheerful music", "on-camera presenters"],
    agentNotes:
      "Reported: visual change every 3-5s; 10-15 min rise-and-fall script; licensed stock + archival + maps behind a dramatic VO (130-150 wpm, deep and measured). Every still gets Ken Burns (1.00->1.10 over ~5s, alternate in/out, 2-5% pan) or a 2.5D cutout parallax. Mark evidence with red circles/arrows, names and dates in small caps. Chapter cards every 2-4 minutes. Never invent historical imagery; label AI or illustrative visuals clearly.",
  },
  {
    id: "gaming-montage",
    name: "Gaming montage",
    category: "genre",
    archetype: "music_montage",
    description:
      "Kill montage cut to phonk/trap: highlights land on drops, 2-3 frame shakes and flashes, velocity ramps, unified punchy grade.",
    inspiredBy: "Fortnite / Valorant / Call of Duty montage edits",
    tags: ["gaming", "montage", "fortnite", "valorant", "kills", "phonk", "highlights"],
    format: {
      aspect: "16:9",
      fps: 60,
      durationSec: { min: 30, typical: 60, max: 180 },
    },
    pacing: {
      aslSec: 2.5, // reported: 3-8s raw clips trimmed to the core
      cutStyle: "beat",
      beatSync: "strict",
      maxSilenceMs: 0,
      keepFillers: false,
      hook: "Best clip first: the cleanest multi-kill lands on the first drop within 5s.",
      ending: "abrupt",
    },
    grade: {
      exposure: 0,
      contrast: 1.2,
      saturation: 1.2,
      vibrance: 0.15,
      temperature: 0,
      tint: 0,
      highlights: -0.05,
      shadows: -0.1,
      fade: 0,
      lut: "vivid-pop",
      vignette: 0.25,
      grain: 0,
      chromaticAberration: 3,
      look: "punchy unified game color with darkened edges",
    },
    palette: {
      background: "#05050A",
      foreground: "#FFFFFF",
      accents: ["#00F0FF", "#FF2E63", "#F9F871"],
      rule: "neon accents for killfeed and callouts",
    },
    typography: {
      title: {
        fontFamily: "Russo One",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: 0.04,
        color: "#FFFFFF",
        shadow: { color: "rgba(0,240,255,0.6)", blur: 12, x: 0, y: 0 },
        sizePctH: 9,
      },
      body: {
        fontFamily: "Rubik",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.02,
        color: "#FFFFFF",
        sizePctH: 3.2,
      },
      callout: {
        fontFamily: "Orbitron",
        fontWeight: 800,
        textTransform: "uppercase",
        letterSpacing: 0.06,
        color: "#00F0FF",
        sizePctH: 5,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Russo One",
        fontWeight: 400,
        fontSize: 56,
        color: "#FFFFFF",
        activeColor: "#00F0FF",
        textTransform: "uppercase",
        stroke: { color: "#000000", width: 4 },
        animation: "pop",
        combineMs: 400,
        maxWordsPerPage: 3,
      },
      yPct: 0.8,
    },
    transitions: {
      primary: "cut",
      secondary: ["flash", "zoom-in", "glitch", "whip"],
      durationFrames: 3,
      frequency: 0.4,
      avoid: ["shakes longer than 3 frames", "cuts off the beat", "dead time before kills", "mismatched color between games"],
    },
    motion: {
      enter: "zoom",
      exit: "glitch",
      easing: "snappy",
      textAnimation: "slam",
      textUnit: "word",
      stagger: 2,
      kenBurns: false,
      shake: true,
      motionBlur: true,
      overshootPct: 10,
    },
    overlays: ["kinetic-title", "counter", "logo-reveal", "killfeed callout"],
    sound: {
      music: "phonk / trap / dubstep with hard drops",
      bpm: [140, 160],
      sfx: ["impact", "whoosh", "bass-hit", "sub-drop", "glitch"],
      sfxPerMin: 30,
      duckDb: 6,
    },
    signature: [
      "Kills and impacts land exactly on the hardest beats",
      "2-3 frame camera shakes and white flashes on landing cuts",
      "Slow motion just before the climax, released on the beat",
      "Unified punchy grade with darkened edges across games",
    ],
    avoid: ["long shakes (motion sickness)", "unsynced cuts", "letting clips run past the highlight"],
    agentNotes:
      "Reported workflow: trim each clip to ~3-8s starting just before its climax; cut on strong beats and use zooms/shakes on weak beats instead of extra cuts; land the hardest kill on the hardest drop; shake max 2-3 frames; white flash on the beat where the cut lands; slow-mo right before the climax then release to normal speed on the beat; darken the edges and unify color across games. Start a beginner edit with 6-8 clips on a 30s track. Export 60fps for YouTube, 1080x1920 for Shorts.",
  },
  {
    id: "real-estate-tour",
    name: "Real estate tour",
    category: "genre",
    archetype: "event_or_property",
    description:
      "Listing walkthrough: drone establishing shot, smooth room-to-room gimbal glides, bright neutral grade, clean property-spec lower thirds.",
    inspiredBy: "Real estate listing videos",
    tags: ["real estate", "property", "house tour", "listing", "drone", "luxury", "walkthrough"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 30, typical: 120, max: 300 },
    },
    pacing: {
      aslSec: 3.5, // reported: wides 3-5s, details 2-3s, hero views 5-7s
      cutStyle: "beat",
      beatSync: "loose",
      maxSilenceMs: 0,
      keepFillers: false,
      hook: "Hero exterior or drone reveal with the address and price on screen in the first 3-5s.",
      ending: "cta",
    },
    grade: {
      exposure: 0.2,
      contrast: 1.05,
      saturation: 1.05,
      vibrance: 0.1,
      temperature: 0.03,
      tint: 0,
      highlights: -0.35,
      shadows: 0.15,
      fade: 0,
      vignette: 0,
      grain: 0,
      look: "bright, clean, true to life: windows recovered (HDR), verticals straight",
    },
    palette: {
      background: "#FFFFFF",
      foreground: "#1A1A1A",
      accents: ["#B08D57", "#1F3A5F"],
      rule: "brokerage colors in lower thirds only",
    },
    typography: {
      title: {
        fontFamily: "Montserrat",
        fontWeight: 500,
        textTransform: "uppercase",
        letterSpacing: 0.12,
        color: "#FFFFFF",
        sizePctH: 5,
      },
      body: {
        fontFamily: "Lato",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: 0.02,
        color: "#FFFFFF",
        sizePctH: 3,
      },
      callout: {
        fontFamily: "Montserrat",
        fontWeight: 600,
        textTransform: "uppercase",
        letterSpacing: 0.08,
        color: "#B08D57",
        sizePctH: 3.4,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Lato",
        fontWeight: 700,
        fontSize: 44,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "none",
        background: { color: "rgba(26,26,26,0.7)", padding: 12, radius: 4 },
        animation: "fade",
        combineMs: 1200,
        maxWordsPerPage: 8,
      },
      yPct: 0.88,
    },
    transitions: {
      primary: "cut",
      secondary: ["fade"],
      durationFrames: 12,
      frequency: 0.2,
      avoid: ["script fonts", "drop shadows", "heavy text animation", "whips, spins or glitches", "fisheye distortion"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "ease-in-out",
      textAnimation: "fade",
      textUnit: "line",
      stagger: 4,
      idleLoop: "drift",
      kenBurns: true,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["lower-third", "spec-card", "map-route", "logo-reveal", "end-card"],
    sound: {
      music: "80-100 BPM luxury (piano / ambient house) or 120-140 BPM energetic modern pop",
      bpm: [80, 140],
      sfx: [],
      sfxPerMin: 0,
      duckDb: 14,
    },
    signature: [
      "Drone establishing shot, then exterior -> entry -> living -> kitchen -> bedrooms -> baths -> outdoor",
      "Slow, smooth gimbal glides and slider reveals",
      "Bright neutral grade with recovered window views",
      "Clean lower thirds: address, price, beds/baths/sqft, agent and brokerage",
    ],
    avoid: ["script fonts and drop shadows", "centered text over rooms", "shaky handheld", "over-fast cutting that hides the layout"],
    agentNotes:
      "Reported: wide shots 3-5s, details 2-3s, hero views 5-7s; order exterior -> entry -> living -> kitchen -> bedrooms -> bathrooms -> backyard -> aerial; cut on downbeats. 80-100 BPM feels luxurious, 120-140 BPM energetic. Lower thirds at top or bottom (never centered): address, price, beds/baths/sqft, agent, brokerage - clean sans, no shadows. Under 3 min for social, up to 5 for MLS, 9:16 cut under 45s. Warm grade for family homes, cooler/cleaner for modern.",
  },
  {
    id: "wedding-film",
    name: "Wedding film",
    category: "genre",
    archetype: "event_or_property",
    description:
      "Cinematic wedding highlight: vows as voiceover, golden-hour slow motion, soft lifted pastels, letterbox and gentle dissolves.",
    inspiredBy: "Cinematic wedding highlight films",
    tags: ["wedding", "cinematic", "highlight film", "romantic", "slow motion", "vows", "event"],
    format: {
      aspect: "16:9",
      fps: 24,
      durationSec: { min: 45, typical: 240, max: 360 },
      letterbox: 2.39,
    },
    pacing: {
      aslSec: 3,
      cutStyle: "mixed",
      beatSync: "loose",
      maxSilenceMs: 0,
      keepFillers: true,
      hook: "Open on a line from the vows or a letter (audio first, over black or detail shots), then the golden-hour couple shot as the music enters.",
      ending: "outro_card",
    },
    grade: {
      exposure: 0.1,
      contrast: 0.92,
      saturation: 0.88,
      vibrance: 0.05,
      temperature: 0.12,
      tint: 0.03,
      highlights: -0.3,
      shadows: 0.12,
      fade: 0.1,
      lut: "portra",
      vignette: 0.1,
      grain: 0.1,
      glow: 0.15,
      look: "soft romantic film: lifted shadows, gentle highlights, warm skin, pastel",
    },
    palette: {
      background: "#F6F0E8",
      foreground: "#3A3330",
      accents: ["#E8C7C8", "#C9B79C", "#FFFFFF"],
      rule: "cream, blush and champagne; white serif titles",
    },
    typography: {
      title: {
        fontFamily: "Cormorant Garamond",
        fontWeight: 300,
        textTransform: "uppercase",
        letterSpacing: 0.15,
        color: "#FFFFFF",
        sizePctH: 6,
      },
      body: {
        fontFamily: "Cormorant Garamond",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: 0.02,
        color: "#FFFFFF",
        italic: true,
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Great Vibes",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: 0,
        color: "#FFFFFF",
        sizePctH: 8,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Cormorant Garamond",
        fontWeight: 500,
        fontSize: 48,
        color: "#FFFFFF",
        activeColor: "#FFFFFF",
        textTransform: "none",
        shadow: { color: "rgba(0,0,0,0.35)", blur: 10, x: 0, y: 2 },
        animation: "fade",
        combineMs: 1800,
        maxWordsPerPage: 10,
      },
      yPct: 0.86,
    },
    transitions: {
      primary: "fade",
      secondary: ["dip-to-white", "light-leak"],
      durationFrames: 16,
      frequency: 0.4,
      avoid: ["whips, glitches or zoom punches", "harsh contrast", "fast montage cutting", "trendy meme SFX"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "gentle",
      textAnimation: "fade",
      textUnit: "line",
      stagger: 6,
      idleLoop: "drift",
      kenBurns: true,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["letterbox", "kinetic-title", "end-card", "film-burn"],
    sound: {
      music: "piano / strings / indie-folk building to a swell at the vows or the kiss",
      bpm: [70, 100],
      sfx: [],
      sfxPerMin: 0,
      duckDb: 12,
    },
    signature: [
      "Vows, speeches or letters used as narrative voiceover",
      "Golden-hour slow motion (60fps conformed to 24)",
      "Soft lifted pastels: lifted shadows, gentle highlights, warm skin",
      "2.39 letterbox, slow dissolves and dips to white",
    ],
    avoid: ["chronological slideshow structure", "punchy commercial grades", "hard flash transitions"],
    agentNotes:
      "Structure for emotion, not chronology: audio-first vow line -> getting ready details -> ceremony (vow audio carries the edit) -> portraits in golden-hour slow motion -> party energy lift -> the kiss/exit on the music swell -> names + date card. Shots 2-4s, slow-mo 40-50% speed, dissolves 12-20 frames, occasional dip to white or light leak. Titles: names in a thin wide-tracked serif, date small beneath, 1s fades. Keep ambient room tone under the music.",
  },
  {
    id: "lofi-aesthetic",
    name: "Lo-fi aesthetic",
    category: "genre",
    archetype: "retro_texture",
    description:
      "Cozy lo-fi loop: anime study-room vibe, warm faded grain, rain and steam micro-loops, tiny now-playing text, vinyl-crackle beats.",
    inspiredBy: "Lo-fi hip hop study streams",
    tags: ["lofi", "chill", "study", "anime", "cozy", "loop", "aesthetic"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 15, typical: 120, max: 10800 },
    },
    pacing: {
      aslSec: 8,
      cutStyle: "continuous",
      beatSync: "loose",
      maxSilenceMs: 0,
      keepFillers: true,
      hook: "No hard hook: the loop is already in motion on frame 0 with the beat; a small now-playing card fades in after ~2s.",
      ending: "loop",
    },
    grade: {
      exposure: 0,
      contrast: 0.85,
      saturation: 0.8,
      vibrance: -0.05,
      temperature: 0.12,
      tint: 0.05,
      highlights: -0.15,
      shadows: 0.1,
      fade: 0.14,
      lut: "matte-fade",
      vignette: 0.3,
      grain: 0.25,
      glow: 0.15,
      look: "warm faded: amber, dusty purple, muted teal, soft grain and halation",
    },
    palette: {
      background: "#2B2235",
      foreground: "#F3E9DC",
      accents: ["#E8A87C", "#8E7DBE", "#7FB5B0"],
      rule: "warm ambers, dusty purples, muted teals",
    },
    typography: {
      title: {
        fontFamily: "Space Mono",
        fontWeight: 400,
        textTransform: "lowercase",
        letterSpacing: 0.02,
        color: "#F3E9DC",
        sizePctH: 3,
      },
      body: {
        fontFamily: "Lora",
        fontWeight: 400,
        textTransform: "lowercase",
        letterSpacing: 0.01,
        color: "#F3E9DC",
        italic: true,
        sizePctH: 2.8,
      },
      callout: {
        fontFamily: "Courier Prime",
        fontWeight: 400,
        textTransform: "lowercase",
        letterSpacing: 0.02,
        color: "#E8A87C",
        sizePctH: 2.8,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Space Mono",
        fontWeight: 400,
        fontSize: 40,
        color: "#F3E9DC",
        activeColor: "#F3E9DC",
        textTransform: "lowercase",
        animation: "fade",
        combineMs: 2000,
        maxWordsPerPage: 8,
      },
      yPct: 0.88,
    },
    transitions: {
      primary: "fade",
      secondary: ["dip-to-black"],
      durationFrames: 45,
      frequency: 0.9,
      avoid: ["hard cuts inside the loop", "saturated color", "fast motion", "bold headlines"],
    },
    motion: {
      enter: "fade",
      exit: "fade",
      easing: "gentle",
      textAnimation: "fade",
      textUnit: "line",
      stagger: 8,
      idleLoop: "breathe",
      kenBurns: true,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: ["vhs-overlay", "now-playing card", "rain on glass", "dust and scratches", "small audio visualizer bars"],
    sound: {
      music: "lo-fi hip-hop with vinyl crackle, tape saturation and rain ambience",
      bpm: [70, 90],
      sfx: [],
      sfxPerMin: 0,
      duckDb: 8,
    },
    signature: [
      "Anime study-room (or cafe/window) scene with seamless 3-6s micro-loops",
      "Warm faded palette: amber, dusty purple, muted teal",
      "Soft grain, halation and low-opacity VHS noise",
      "Tiny lowercase now-playing text",
    ],
    avoid: ["hard cuts", "big bold type", "fast camera moves", "high contrast"],
    agentNotes:
      "Reported core: warm muted color, soft film grain, gentle lamp light, a calm everyday setting (desk, cafe, windowsill). Animate only small loops - rain on glass, steam from a cup, curtains, a cat's tail, flickering lamp - as seamless 3-6s cycles; 2-3 layer parallax; very slow Ken Burns (1.00->1.03 over 20s). Grain/VHS noise layer at low opacity. Text is a tiny lowercase now-playing card bottom-left. Music 70-90 BPM lo-fi hip-hop with vinyl crackle.",
  },
  {
    id: "motion-showreel",
    name: "Motion showreel",
    category: "genre",
    archetype: "music_montage",
    description: "15-second motion-design reel: dark canvas, music only, hard cuts on downbeats, shape morphs and kinetic type.",
    inspiredBy: "Motion-design studio showreels",
    tags: ["showreel", "motion design", "kinetic typography", "reel", "dark", "shape morph", "ai video"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 10, typical: 15, max: 30 },
    },
    pacing: {
      aslSec: 1,
      cutStyle: "beat",
      beatSync: "strict",
      maxSilenceMs: 0,
      keepFillers: false,
      hook: "Frame 0 is already moving: a bold shape morph or a giant word slams on the first downbeat - no fade-in from black.",
      ending: "logo_sting",
    },
    grade: {
      exposure: 0,
      contrast: 1.1,
      saturation: 1.05,
      vibrance: 0,
      temperature: 0,
      tint: 0,
      highlights: 0,
      shadows: -0.05,
      fade: 0,
      vignette: 0.2,
      grain: 0.04,
      glow: 0.2,
      look: "dark graphic: near-black canvas, one hot accent, subtle grain and glow",
    },
    palette: {
      background: "#0A0A0B",
      foreground: "#F5F5F5",
      accents: ["#FF4D00", "#F5F5F5"],
      rule: "one accent on neutrals; extreme type-scale contrast",
    },
    typography: {
      title: {
        fontFamily: "Archivo Black",
        fontWeight: 400,
        textTransform: "uppercase",
        letterSpacing: -0.03,
        lineHeight: 0.9,
        color: "#F5F5F5",
        sizePctH: 22,
      },
      body: {
        fontFamily: "Inter",
        fontWeight: 500,
        textTransform: "uppercase",
        letterSpacing: 0.12,
        color: "#A3A3A3",
        sizePctH: 2.8,
      },
      callout: {
        fontFamily: "Space Grotesk",
        fontWeight: 700,
        textTransform: "uppercase",
        letterSpacing: -0.02,
        color: "#FF4D00",
        sizePctH: 10,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Inter",
        fontWeight: 600,
        fontSize: 44,
        color: "#F5F5F5",
        activeColor: "#FF4D00",
        textTransform: "uppercase",
        animation: "none",
        combineMs: 600,
        maxWordsPerPage: 3,
        letterSpacing: 0.1,
      },
      yPct: 0.86,
    },
    transitions: {
      primary: "cut",
      secondary: ["wipe", "zoom-in", "flash", "iris"],
      durationFrames: 6,
      frequency: 0.3,
      avoid: [
        "fading every scene in and out",
        "tweening inside one static scene instead of cutting",
        "particles, neon and random shake",
        "a centered headline on a purple-to-blue gradient",
      ],
    },
    motion: {
      enter: "mask-reveal",
      exit: "stretch",
      easing: "smooth",
      textAnimation: "mask-up",
      textUnit: "word",
      stagger: 2,
      idleLoop: "drift",
      kenBurns: false,
      shake: false,
      motionBlur: true,
      overshootPct: 0,
    },
    overlays: ["kinetic-title", "logo-reveal", "grid-background", "light-sweep", "shape morph"],
    sound: {
      music: "music only: punchy electronic or percussive cinematic with a clear downbeat grid",
      bpm: [110, 130],
      sfx: ["whoosh", "impact", "click", "glitch"],
      sfxPerMin: 40,
      duckDb: 0,
    },
    signature: [
      "Hard cuts on downbeats between shots (not one long tween)",
      "Giant kinetic type with extreme scale contrast",
      "Shape morphs and masked reveals on a dark canvas",
      "Something new every 1-2s, ending on a logo sting",
    ],
    avoid: ["slideshow of static scenes", "everything fading in", "dead beats with nothing moving", "more than one accent color"],
    agentNotes:
      "Research: 15s, dark, music-only, beat cuts, shape morphs, kinetic type. Beat-map the track; cut every 1-2 beats (~1s) between distinct compositions rather than animating inside one scene. Each shot: one bold idea (a word at 15-25% of frame height, a morphing shape, a grid sweep) with masked reveals and expo-out easing, zero overshoot. One accent color on near-black, 3-5% grain, restrained glow. Sound hits on every cut; end on the logo 1-2s before the music resolves.",
  },
  {
    id: "data-story",
    name: "Data story",
    category: "genre",
    archetype: "edu_animation",
    description:
      "Animated data story: counters with K/M/% formatting, staggered bars, line draw-ons and glass stat cards on a dark canvas.",
    inspiredBy: "Data journalism and 'Wrapped'-style stat videos",
    tags: ["data", "charts", "statistics", "counters", "infographic", "wrapped", "dashboard"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 15, typical: 45, max: 120 },
    },
    pacing: {
      aslSec: 3,
      cutStyle: "mixed",
      beatSync: "loose",
      maxSilenceMs: 250,
      keepFillers: false,
      hook: "Lead with the single most surprising number counting up big and centered within 2s, one line of context underneath.",
      ending: "cta",
    },
    grade: {
      exposure: 0,
      contrast: 1.05,
      saturation: 1.05,
      vibrance: 0.05,
      temperature: 0,
      tint: 0,
      highlights: 0,
      shadows: 0,
      fade: 0,
      vignette: 0.15,
      grain: 0.03,
      glow: 0.15,
      look: "clean dark data canvas with soft glows behind glass cards",
    },
    palette: {
      background: "#0B0D12",
      foreground: "#F4F6FA",
      accents: ["#4ADE80", "#60A5FA", "#F472B6", "#FBBF24"],
      rule: "neutral dark canvas; one accent per series, the key datum highlighted, the rest gray",
    },
    typography: {
      title: {
        fontFamily: "Inter Tight",
        fontWeight: 700,
        textTransform: "none",
        letterSpacing: -0.03,
        color: "#F4F6FA",
        sizePctH: 7,
      },
      body: {
        fontFamily: "Inter",
        fontWeight: 500,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#9AA4B2",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Inter Tight",
        fontWeight: 800,
        textTransform: "none",
        letterSpacing: -0.04,
        color: "#4ADE80",
        sizePctH: 16,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Inter",
        fontWeight: 600,
        fontSize: 44,
        color: "#F4F6FA",
        activeColor: "#F4F6FA",
        emphasisColor: "#4ADE80",
        textTransform: "none",
        animation: "fade",
        combineMs: 1200,
        maxWordsPerPage: 8,
      },
      yPct: 0.88,
    },
    transitions: {
      primary: "cut",
      secondary: ["push", "blur", "zoom-in"],
      durationFrames: 10,
      frequency: 0.3,
      avoid: ["3D pie charts", "unlabeled axes", "more than 4 colors per chart", "numbers without context"],
    },
    motion: {
      enter: "rise",
      exit: "fade",
      easing: "smooth",
      textAnimation: "rise",
      textUnit: "word",
      stagger: 2,
      idleLoop: "float",
      kenBurns: false,
      shake: false,
      motionBlur: false,
      overshootPct: 3,
    },
    overlays: ["counter", "bar-chart", "line-chart", "stat-grid", "progress-bar", "kinetic-title", "grid-background"],
    sound: {
      music: "clean minimal electronic with light percussion",
      bpm: [100, 120],
      sfx: ["tick", "pop", "whoosh", "ding"],
      sfxPerMin: 15,
      duckDb: 14,
    },
    signature: [
      "Big counters with K/M/% formatting that tick up with soft ticks",
      "Bars rising with 50-80ms staggers; lines drawing on left to right",
      "Glass stat cards with one highlighted datum",
      "One insight per scene, each number with one line of context",
    ],
    avoid: ["chart junk and 3D effects", "tiny labels (<28px at 1080p)", "rainbow palettes", "static charts that never animate"],
    agentNotes:
      "One insight per scene: headline (the takeaway, not the metric name) + one chart. Counters ease out over 0.8-1.5s with K/M/% formatting and a tick SFX at the end; bars rise with 50-80ms staggers; lines draw on left to right, then the key point gets a dot + label. Glass cards: 8-12% white fill, 1px border, 24px blur. Highlight the key datum in the accent and gray the rest. Labels >=28px, body >=36px, headlines >=56px at 1080p. Use real data only; cite the source in a small footer.",
  },
  {
    id: "article-highlight-documentary",
    name: "Article highlight documentary",
    category: "genre",
    archetype: "doc_essay",
    description:
      "Evidence-on-screen doc style: a news article in slow 3D tilt, the rest blurred, a highlighter sweeping the key quote as the VO reads it.",
    inspiredBy: "Vox / Johnny Harris-style article pulls",
    tags: ["documentary", "article", "highlight", "news", "evidence", "explainer", "highlighter"],
    format: {
      aspect: "16:9",
      fps: 30,
      durationSec: { min: 15, typical: 60, max: 900 },
    },
    pacing: {
      aslSec: 5,
      cutStyle: "mixed",
      beatSync: "none",
      maxSilenceMs: 300,
      keepFillers: false,
      hook: "Open on the headline itself: the article in slow 3D tilt, everything else blurred, the key sentence highlighted as the narrator reads it (0-5s).",
      ending: "fade",
    },
    grade: {
      exposure: 0,
      contrast: 1.08,
      saturation: 0.85,
      vibrance: -0.05,
      temperature: 0.03,
      tint: 0,
      highlights: -0.15,
      shadows: 0.03,
      fade: 0.06,
      lut: "matte-fade",
      vignette: 0.3,
      grain: 0.2,
      look: "muted editorial: paper whites, soft vignette, grain",
    },
    palette: {
      background: "#121212",
      foreground: "#F4F1EA",
      accents: ["#FFF200", "#D62828"],
      rule: "paper and ink; highlighter yellow for the quote, red for circles",
    },
    typography: {
      title: {
        fontFamily: "Oswald",
        fontWeight: 700,
        textTransform: "uppercase",
        letterSpacing: 0.01,
        color: "#F4F1EA",
        shadow: { color: "rgba(0,0,0,0.5)", blur: 12, x: 0, y: 4 },
        sizePctH: 8,
      },
      body: {
        fontFamily: "Source Serif 4",
        originalFont: "newspaper body serif",
        fontWeight: 400,
        textTransform: "none",
        letterSpacing: -0.005,
        color: "#1A1A1A",
        sizePctH: 3.4,
      },
      callout: {
        fontFamily: "Playfair Display",
        originalFont: "newspaper headline serif",
        fontWeight: 700,
        textTransform: "none",
        letterSpacing: -0.01,
        color: "#1A1A1A",
        italic: true,
        sizePctH: 5,
      },
    },
    captions: {
      mode: "none",
      style: {
        fontFamily: "Source Serif 4",
        fontWeight: 600,
        fontSize: 48,
        color: "#1A1A1A",
        activeColor: "#1A1A1A",
        activeBackground: "#FFF200",
        textTransform: "none",
        animation: "highlight-box",
        combineMs: 1400,
        maxWordsPerPage: 10,
      },
      yPct: 0.5,
    },
    transitions: {
      primary: "cut",
      secondary: ["blur", "zoom-in", "fade"],
      durationFrames: 12,
      frequency: 0.3,
      avoid: ["fake or invented articles", "flat full-screen screenshots without depth", "bouncy motion", "neon colors"],
    },
    motion: {
      enter: "rise-blur",
      exit: "blur",
      easing: "ease-in-out",
      textAnimation: "highlight",
      textUnit: "line",
      stagger: 6,
      idleLoop: "drift",
      kenBurns: true,
      shake: false,
      motionBlur: false,
      overshootPct: 0,
    },
    overlays: [
      "highlighter-sweep",
      "paper-texture",
      "circle-highlight",
      "quote-card",
      "browser-window",
      "social-post",
      "blurred article page in slow 3D tilt",
    ],
    sound: {
      music: "tense documentary bed: low pulses and sparse piano",
      bpm: [70, 95],
      sfx: ["paper", "whoosh", "tick", "sub-drop"],
      sfxPerMin: 8,
      duckDb: 16,
    },
    signature: [
      "Real article on a slowly tilting 3D plane (rotateX/Y 8-15deg) with depth-of-field blur",
      "Everything but the key passage blurred and darkened",
      "Highlighter sweep timed to the narrator reading the line",
      "Grain, vignette and paper texture for an editorial feel",
    ],
    avoid: ["fabricated headlines or sources", "unreadable small text", "highlighting more than one sentence at a time"],
    agentNotes:
      "Research: blurred article, slow 3D tilt, highlighter sweep. Use a real screenshot or capture of the article (never invent one; show the outlet and date). Place it on a 3D plane tilted 8-15deg, drift the camera slowly (push 1.00->1.06 over the shot), blur/darken everything except the target passage (6-10px blur, 40% dim), then sweep #FFF200 at ~70% multiply across the line over 300-600ms exactly as the VO reads it. Add red circles for names/numbers. Grain 0.2, vignette 0.3.",
  },
];
